### ISSUE TITLE
Find a better image to replace the terrible icon I am using for Discourse/etc links

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1008]
Better = Bigger and cleaner-looking

**Comment by stevejalim** [comment]
@valgrimm I can help - DM me what tours using and where

**Comment by valgrimm** [comment]
The image is https://devportal-media-prod.s3.amazonaws.com/images/bubble.width-320.png and I'm using it on the Browser Extensions and Voice topics pages.

**Comment by valgrimm** [comment]
fixed
