### ISSUE TITLE
Remove Javascript and CSS Topics, but if possible retain tags

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1009]
Our guidance for 2020 is to remove topics (to be Products and Technologies) without stakeholders, as one of our metrics, the key one, is making the products and technologies stakeholders happy. 

However, it would be nice to keep these topics to tag related things without having topic pages if possible. 

Unfortunately, unpublishing the page makes the topic unavailable to tag events, videos, posts with. Publishing it but taking it out of the menu does not remove it  from the Topics tileset on the homepage. I tested this on Dev.
Is it worth the effort of trying to retain this as a tag?

**Comment by stevejalim** [comment]
@valgrimm I'd need to check, but am pretty sure we can add a small bit of code to check if a topic has 'show in menus' set when choosing the topic tiles and hten include/exclude the tile accordingly.

If that sounds OK to you, I can get that done pretty much right away

**Comment by valgrimm** [comment]
That would be spectacular. I don't know if we should ask Kadir before you spending dev time, but if it takes less than 30 minutes I figure he won't mind. Super!!

**Comment by atopal** [comment]
Let's do a filtered version of the topics page

**Comment by stevejalim** [comment]
Waiting for go-ahead on this from @valgrimm based on conversations she's having with Chris

**Comment by valgrimm** [comment]
Not getting rid of Javascript and CSS topics. However, behavior for tags will change. Closing ticket.
