### ISSUE TITLE
Update GA codes when moving to prod

### ISSUE THREAD

**Issue by tobinmori** [mdn/developer-portal#101]
Will need to obtain GA codes from Mozilla analytics team. . ., then give to @stevejalim

**Comment by atopal** [comment]
Was this resolved already? I've done this once for the insights landing page.

**Comment by atopal** [comment]
Alternatively we can ask in #analytics

**Comment by limed** [comment]
I seem to have remembered deploying a GA code for this app already, was this not the right one?

**Comment by stevejalim** [comment]
@tobinmori Is this still in need of attention, please?

**Comment by tobinmori** [comment]
In mid August, I obtained a GA code for DevPortal staging. Do we require a new one for prod? If so, sghose (on Slack) is our point person; he's on the Mozilla analytics team. Can you reach out to him @stevejalim if you require a new code?

**Comment by stevejalim** [comment]
Status update:

So, at the moment there is a GA code setup and in use on staging, and the same code is currently configured to be used in production (when we launch).

The suggestion from `sghose` in Slack is to simply re-purpose the same code for Production and drop out the code from staging.

@atopal Does that work for you? If so, I can make 'remove GA code from staging' a go-live task so we still keep analytics in staging to test instrumentation until we launch

**Comment by atopal** [comment]
sounds good to me Steve!

**Comment by limed** [comment]
> Status update:
> 
> So, at the moment there is a GA code setup and in use on staging, and the same code is currently configured to be used in production (when we launch).
> 
> The suggestion from `sghose` in Slack is to simply re-purpose the same code for Production and drop out the code from staging.

I'm not familiar with how GA works but if we drop it for stage will it cause an issue with the code if we don't include the GA token? I'm assuming you can just include a conditional in the code for stage?

**Comment by stevejalim** [comment]
> I'm assuming you can just include a conditional in the code for stage?

Yeah, that's a great point. Will do a quick PR for that now

**Comment by stevejalim** [comment]
Existing Code has been re-mapped to Production. #642 will ensure we only include it in the static site, not the CMS's live-rendered pages
