### ISSUE TITLE
Change or remove text header of Topics panel

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1010]
Right now the text header in the Topics panel reads:
"Browse by topic"

Could this be easily changed to "Browse Products and Technologies" or removed?

AC / areas to fix:
- [x] "Browse by topic" on homepage
- [x] "Browse by topic" on topics list
- [ ] Video page "Read more on this topic"
- [ ] Post page "Read more on this topic"
- [x] Posts filters "Topic"
- [x] Events filters "Topic"
- [x] People filters "Topic"
- [x] Person page "Topics I specialize in"

**Comment by stevejalim** [comment]
@valgrimm Yep, can def be changed. What's your preference: rename or remove?

**Comment by valgrimm** [comment]
Rename is definitely my preference.

**Comment by stevejalim** [comment]
I'll see if i can get it to pull in whatever the _title_ of the page currently known as "Topics"

**Comment by valgrimm** [comment]
works for me

**Comment by stevejalim** [comment]
@valgrimm This change to "using whatever the Topics page is called" is now live, so if you rename Topics to Products & Technologies, you will see the phrasing update elsewhere in the site, too

**Comment by valgrimm** [comment]
Fixed. Thanks! (:
