### ISSUE TITLE
Nav reflow/overflow - needs addressing?

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1011]
The change to "Products and Technologies" and the addition of "About" in the Nav means it reflows and gives us a lot of whitespace in the main nav and kind of takes us off-brand (compare to https://protocol.mozilla.org/demos/navigation.html)

![Screenshot 2019-12-19 at 13.16.38.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/15a1c119-fe97-4a72-bc39-82d0fe901ddd)

If we want to remove that whitespace, we could

* move "About" down in to the footer
* rephase "MDN Web Docs" as just "MDN" (if that's not against brand rules)
* rephrase "Products and Technologies" to just "Technologies" (if that's not going against stakeholder requests)

What do you both think @valgrimm @atopal ?

**Comment by valgrimm** [comment]
I propose changing "MDN Web Docs" in the menu to just "MDN Docs" if that would save enough room? Otherwise we could change it to just "MDN", but I'm not totally sure about that, Kadir can make that call better than I. Moving About to the footer is also a great option, because people are only ever going to go to About once.

**Comment by valgrimm** [comment]
Although I am not sure if we need to consult with Havi and Ali about moving About to the footer.

**Comment by atopal** [comment]
@stevejalim is this at a certain width? Does changing "Products and Technologies" to "Products & Technologies" help? If we have to shorten MDN Web Docs, let's go with just MDN.

**Comment by stevejalim** [comment]
Ah ha - playing about with it, it looks like this might be fixable with CSS, as the reflow happens at max/unrestricted width, then disappears (behaves correctly) at a smaller viewport width before naturally overflowing at an even narrower viewport.

So, I can assing this toI still this to me for a dev fix, but it is still pretty busy. 

@atopal am tempted to go with the ampersand change and dropping "Web Docs" from the MDN link, too.

Will PR it and push it to dev and you can see what you think.

Adding to this sprint, but lower priority

**Comment by valgrimm** [comment]
Changed the ampersand.

**Comment by atopal** [comment]
@stevejalim I think it's a layout thing. Reducing it to MDN doesn't fix the issue btw. I'd give this higher priority, since it's a pretty visible regression.

**Comment by stevejalim** [comment]
Ah yeah, sorry - forgot to send on my reply to this. Yes it's
layout-related. Will make a P1 and address either Monday or this weekend,
if I can...

**Comment by atopal** [comment]
Please don't do it over the week end. Monday is totally fine.

**Comment by atopal** [comment]
Oh wait, you're on PTO then, nevermind, it's not urgent enough to do that then.

@valgrimm Val, can we change it back to Topics in the mean time?

**Comment by valgrimm** [comment]
Yup
