### ISSUE TITLE
Implement automated blog+YouTube syndication

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1017]
Ideally, syndicating developer-relevant blogs from around Mozilla on the portal is part of the goals for 2020. 
A content task to identify relevant blogs was also created (see #1016). 

Revised AC: 
At an interval of two hours for YouTube and 30min for blogs (can correct timing if unrealistic).
- [ ] Entry-level: Posts from relevant blogs+YouTube channels (manually added to a list in code somewhere) are automatically added as "External Posts" on the portal. 
- [ ] Mid-level: Social sharing image associated with each post is automatically filled into image field so the placeholder image doesn't have to be replaced.
- [ ] Fancy-unrealistic-level: A tag is automatically assigned depending on the blog/YouTube.

(Perhaps I should create an Epic to link these tickets).

**Comment by stevejalim** [comment]
Quick estimates, assuming all blogs have an RSS feed (plus CR and acceptance time):
entry level: 1.5 days
mid level: 2 days, inclusive
fancy: 2.5 days, inclusive

Youtube: +0.5 day, as long as RSS feed remains alive: https://www.youtube.com/feeds/videos.xml?channel_id=UCh5UlGiu9d6LegIeUCW4N1w

**Comment by valgrimm** [comment]
Inclusive!
And add YouTube to AC. 
I shall edit ticket title accordingly.

**Comment by valgrimm** [comment]
Now unblocked: I found all the blogs and youtube channels we will have for the near future

**Comment by stevejalim** [comment]
@valgrimm and @havi Quick question: for the automatic post/video ingestion, do you want the things to be automatically published, or simply submitted for moderation?

I'm leaning towards the latter, because it gives us better visibility of what's going up - including a chance to skip any items that we might not want linked to from the portal (for some hand-wavy reason I can't think of right now :smile: )

**Comment by valgrimm** [comment]
I defer this to @havi but generally agree with Steve. Kudos on thinking of this Steve!

**Comment by stevejalim** [comment]
@valgrimm Got another couple of questions: we can pull in data about authors, which I can then try to match with existing `Person` pages we hold. 
1) Do you think this is worth it, when we can clearly match it to a single `Person`? (If there are multiple matches, somehow, I think the only safe move is to not auto-associate a Person with the newly created Page.

2) If we don't have a `Person` page for an author, should we automatically create it, or just ping moderators to say that we could create a page for "Alice McTest" and to associate it with Post-page-that-was-just-made? (My preference is the latter - let's not make this thing too clever just yet). 

Alternative: we could just skip the author data altogether, for now -- I don't know if [m]any external items have author info associated with them right now

**Comment by valgrimm** [comment]
I think this approach sounds fine, including not automatically creating author pages without pinging moderators. Internal items don't generally have author data yet as it wasn't clear who should have profile pages and there isn't a clear use case for author profile pages.
Actually, that's an argument against automatically adding authors for now. @atopal  shall we leave that be for now?

**Comment by stevejalim** [comment]
Ok, will not automatically add authors for now
