### ISSUE TITLE
Enable use of topic tags without pages

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1030]
Javascript and CSS should not have pages as they have no stakeholders.
It is easy to remove them from the topics dropdown menu, but unless they are unpublished they still appear among the topic tiles on the homepage. 
If they are unpublished they cannot be used to tag content.
I wish to retain them to tag content.

AC:
Do not display topics that are not shown in menu among the topics tiles on the homepage.

**Comment by stevejalim** [comment]
@valgrimm Duplicate of #1009 ?

**Comment by valgrimm** [comment]
hahahahah I thought I created this and then could not find it. go me. Thanks (:
