### ISSUE TITLE
Purchase MapBox service

### ISSUE THREAD

**Issue by tobinmori** [mdn/developer-portal#105]

**Comment by tobinmori** [comment]
Currently, free tier being used.

**Comment by tobinmori** [comment]
https://docs.mapbox.com/help/account/invoices/#exceeding-whats-included-in-the-free-tier

**Comment by stevejalim** [comment]
@tobinmori Does this still need action, please? Or is the idea that the free tier will be enough to start with? Looks like adding a card on the relevant account will mean we have a contingency ready as soon as we need it.

**Comment by tobinmori** [comment]
Yes it does @stevejalim. I'll find out about how we pay for this by the end of week. Thanks for the reminder.

**Comment by tobinmori** [comment]
@stevejalim can you let me know which implementation of MapBox we're using. Looks like there are a few possibilities:

https://docs.mapbox.com/accounts/overview/pricing/

**Comment by stevejalim** [comment]
@tobinmori Based on this line 
https://github.com/mdn/developer-portal/blob/bb6ffef4bd9af25c43e7c658f094ae13e4a35c4b/developerportal/apps/events/templates/event.html#L6
it looks like we're using Mapbox GL JS later than 1.0 which is [pricing by map loads](https://docs.mapbox.com/accounts/overview/pricing/#mapbox-gl-js-v100-and-higher)

**Comment by tobinmori** [comment]
Thanks @stevejalim I have submitted a request for this to be setup. Mozilla ref number: INC0028209

**Comment by stevejalim** [comment]
Any news on this?

**Comment by tobinmori** [comment]
@stevejalim No word yet. I just re-pinged them.

**Comment by tobinmori** [comment]
@stevejalim IT responded and said that another team at Moz uses mapbox, so they're looking into how we can share licenses. more to come. . .

**Comment by tobinmori** [comment]
50k MAUs for the free tier.

**Comment by stevejalim** [comment]
@tobinmori Can you guess what I want to ask about this? :D

**Comment by tobinmori** [comment]
Thanks for bumping it up @stevejalim! And please do so w/o any feelings of guilt!
So, I notified Mozilla IT that this is urgent at this point. 

@atopal do you expect over 50k hits on a month on the DevPortal maps?
(because things may map functionality may start failing for users after that threshold is reached)

**Comment by atopal** [comment]
@tobinmori it's really hard to predict traffic to the dev portal at this time. If we can't get access to more views, I'd want to have the ability to turn off the feature.

**Comment by stevejalim** [comment]
> If we can't get access to more views, I'd want to have the ability to turn off the feature.

I can make that a configurable option, no worries.

However, will we know if we hit that threshold -- other than via a bug report? Hopefully the account owner (is that you @tobinmori ?) will get a ping

**Comment by stevejalim** [comment]
Checked in via Service Now thread, above, to see if there's progress on this

**Comment by stevejalim** [comment]
Pay-as-you-go mode now enabled - closing this

**Comment by tobinmori** [comment]
Yep. just chatted with Moz IT, should be good to go! CC card in place.
