### ISSUE TITLE
Make date display optional on post pages 

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1084]
Context:
Currently, the date a post page is created is displayed by default.

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/233850fc-c932-40dd-b4dc-a8fdf366aca3)

We are not currently using post pages for their intended purpose.
Instead, stakeholders use them to create additional pages as needed.
They do not necessarily want dates displayed.

AC: 
In Meta tab, add a tickbox to make date field content display optional. 

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/bde2931b-76d5-48a2-90ca-8b4ba8b19090)

**Comment by stevejalim** [comment]
> We are not currently using post pages for their intended purpose.
> Instead, stakeholders use them to create additional pages as needed.

@valgrimm Why are they not using the `Content Page` as a page option? If it's not available as a child of a particular Page, we can change that so it is.

**Comment by valgrimm** [comment]
There isn't currently a way to add Child pages to topics that I can see. Sorry for delay on responding.
