### ISSUE TITLE
Different robots.txt for Stage/Dev than Production

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1099]
...so that we reduce the chances of dev/stage being indexed, which would cause SEO/SERPs noise

**Comment by stevejalim** [comment]
@atopal Do you think about this ticket - am happy to solve the issue but first want to check that you agree it's a real issue.

**Comment by atopal** [comment]
ideally we add no-index meta tags to all stage pages, and leave the robots.txt alone
