### ISSUE TITLE
Disable Video page blocking error for private YT videos

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1109]
AC:
Be able to create Video pages with the URLs of private YouTube videos

![unpublishedYT-noemederror.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/c83e3feb-658a-43f4-b2bf-c40b48e47dc2)

**Comment by stevejalim** [comment]
@valgrimm If it's not possible to differentiate between a video that is hidden because it's private and a bad URL that doesn't work, are you happy to 'take the risk' of the code change treating them both the same and allowing a save?

Also, piping a non-blocking warning back into the the CMS may not be easy, so would an email notification about "we can't find this video" be tolerable?

**Comment by valgrimm** [comment]
Note, as Steve explained, this is core Wagtail, but we might be able to override it. 

Justification for this functionality: It is not possible to create portal pages for videos in advance of their release. When significant number of YT videos are under embargo, this becomes a problem, as a near-simultaneous launch on Twitter, YT, Hacks blog, and Portal is preferable.

**Comment by stevejalim** [comment]
Note from Wagtail Slack (thanks @zerolab)
>  EmbedBlock returns an EmbedValue which generates its html via wagtail.embeds.format.embed_to_frontend_html which uses a finder to get the embed data (e.g. via oEmbed) so you could define your own finder to tolerate 'unavailable' embeds, by basically not raising `EmbedNotFoundException`s (see https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/embeds/finders/oembed.py#L44)

**Comment by stevejalim** [comment]
And https://wagtail.io/blog/fixing-youtubes-oembed-implementation-custom-finder-class/

**Comment by valgrimm** [comment]
Email notification is great.

**Comment by valgrimm** [comment]
Also, that blog post is encouraging.

**Comment by stevejalim** [comment]
This is quite a rabbit warren, so deferring slightly till i get a clear run at it

**Comment by valgrimm** [comment]
no worries

**Comment by stevejalim** [comment]
As discussed an email thread, we might not need this at all -- once vids are made public on YT, now that we have automatic content ingestion enabled, they will have pages automatically created for them, so the need to pre-create has (potentially..) been made redundant.

@valgrimm if you agree, would you please close this ticket to confirm? Thanks!

**Comment by valgrimm** [comment]
Yes, this is an edge case, and the solution is just to make things unlisted closer to release time and prep links then.
