### ISSUE TITLE
Review current Lighthouse scores and optimise accordingly

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1118]
Perf is slipping from 86 to 78
Accessibility has slipped from 100 to 90

Worth spending couple of hours sorting out.

Easy targets:

- [ ] Cache events data
- [ ] Cache homepage topics (and content in general)
- [ ] Prefetch/dns-prefetch links in the header

**Comment by stevejalim** [comment]
Some of the items highlighted (partic re a11y) are not matching the reality of the HTML we're serving, so I'll have to check again

**Comment by stevejalim** [comment]
Update: now the CDN is cacheing HTML too, we're getting 95/100 for perf

Accessibility is back to 100/100

So, that's encouraging

**Comment by schalkneethling** [comment]
@stevejalim The close button of the task completion survey is missing an accessible name:

```
<button class="mzp-c-notification-bar-button mzp-js-notification-trigger" type="button"></button>
```

We can fix this as follows:

```
<button class="mzp-c-notification-bar-button mzp-js-notification-trigger" type="button">
  <span class="visually-hidden">Close notification</span>
</button>
```

**Comment by stevejalim** [comment]
Closing this now as we'll be circling back with #1118
