### ISSUE TITLE
Check and monitor odd behaviour with auto ingestion

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1132]
1) stage shouldn't have sent a notification message, but it did
2) where's the new content on prod that matches the content that was notified by on stage

**Comment by stevejalim** [comment]
Seems stable - just ingested two more things and notified from both prod and stage, as expected

**Comment by stevejalim** [comment]
Hmm just had it work fine on prod but not invest on stage despite both trying at the same time

Nothing in the monitoring logs

**Comment by stevejalim** [comment]
Leaving this open to gather more info about any unusual behaviour. Ideally we'll get the same messages from stage and from prod announcing they have both imported the same item(s). 

If we don't get that, could you note it here, please, @valgrimm ?

**Comment by valgrimm** [comment]
will do

**Comment by stevejalim** [comment]
Seems stable again. Closing
