### ISSUE TITLE
Task-completion survey: improve UX via more context

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1145]
**"As a website owner, I want to be able to provide more context about the survey, so that people get time to browse the site before they provide feedback"**

Acceptance Criteria:
- If the user clicks the link in the notification, instead of directly triggering the survey to be opened in a new tab, another tab/window is opened which contains messaging explaining the process: 
  * _“When you’re finished with the Developer Portal today, please let us know about your experience.”_
  * The page also shows a link to the survey and a note that the page will automatically change in 30 seconds (counting down)  
  * After 30 seconds, the browser loads in the survey form instead of the initial content

**Comment by schalkneethling** [comment]
![Screenshot 2020-03-27 at 08 44 53](https://user-images.githubusercontent.com/10350960/77729494-79df9800-7007-11ea-9a9e-ad4455a5e76d.png)

Noticed this on mobile when testing another PR. Is this the intended UI for this component on mobile?

I was kinda expecting it to still look as below:

![Screenshot 2020-03-27 at 08 47 23](https://user-images.githubusercontent.com/10350960/77729556-9e3b7480-7007-11ea-9be4-8d9570d7e55e.png)

**Comment by stevejalim** [comment]
Removing from Epic and releasing into general backlog

cc @valgrimm

**Comment by stevejalim** [comment]
Releasing from Epic and putting in icebox
