### ISSUE TITLE
Footer: Fix link to newsletter opt-in page

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1172]
Currently goes to:
https://www.mozilla.org/en-US/newsletter/
Blank except the header

Confirmation page is :
https://www.mozilla.org/en-US/newsletter/developer/

**Comment by valgrimm** [comment]
Weirdly the URL goes to a signup page but the confirmation page appears to be at same URL which means some scripting trickery on page.

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/a5e11dd3-d7fa-4193-bbe6-190b811a263a)

Possibly better to just make link go to signup page. Will email Havi to ask.

**Comment by valgrimm** [comment]
@havi 

We were discussing on email, brought this here for the record. 
It seems the URL for the email confirmation page is the same URL for the official signup form, which means that folks have to fill out the form twice. Havi, would it be ok to just have a signup button in the portal footer that leads to the official email signup form, and not the email field and tickbox?

(The official email signup form page has now changed as well, and requires a country selection, so to save future issues directing folks there might be best, as it is one of many signup pages managed by the email team at the same time, as near as I can tell).

**Comment by stevejalim** [comment]
So, looking at this, it might be that we need to post a selected country in order to get a valid form response at the destination end, which in turn would mean adding and maintaining the same list of countries. (Plus also add the HTML or Text option to our form)

@havi if the UX is acceptable to you, I think @valgrimm's button-that-links-to-the-real-form approach is the most robust in terms of it not silently breaking in the future, plus practical, given I'm temporarily losing access to the project from end of tomorrow

**Comment by stevejalim** [comment]
Blocked on a decision

**Comment by stevejalim** [comment]
Also note that the current newsletter signup page (when you go from developer.mozilla.com) currently gives no indication of success or failure:

![Screenshot 2020-02-06 at 17 07 29](https://user-images.githubusercontent.com/101457/73960703-45066d00-4903-11ea-978d-6b3fdd501a8e.png)

**Comment by stevejalim** [comment]
Talking with Paul (Marketing team developer) over on the side of newsletter code, a bit of a  surprise:

* newsletter signups should be done not as a HTML form that cross-posts to another side, but devportal should be making a JS call to the newsletter service -- so this approach is definitely out of date, and if the newsletter service is expecting JS, that kind of explains why we get no content back when we POST to it

So, I thikn the button option is our best option right now. Even if it might harm conversion.

When we/I have dev time again, we can look at a cleaner solution.

Awaiting thumbs-up, hopefully

**Comment by stevejalim** [comment]
Mocking it up, this is basically what the button solution would look like:

![Screenshot 2020-02-06 at 17 29 19](https://user-images.githubusercontent.com/101457/73962383-3bcacf80-4906-11ea-98aa-9e1736545157.png)

**Comment by stevejalim** [comment]
@valgrimm This is done and deployed. Please close if you're happy!

**Comment by valgrimm** [comment]
Fantastic! Thank you!!
