### ISSUE TITLE
Change "Country" fields to Country or Region

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1177]
Just realized that had not been done, I had read what I thought was there and not what was there. 

per:
https://wiki.mozilla.org/Lists_of_Countries_and_Regions

**Comment by stevejalim** [comment]
Am assuming this only affects Events.

Do we have a no-code-change workaround in the meantime? Such as setting Country to None and entering a string as part of the address?

**Comment by valgrimm** [comment]
Also affects People. 

No workaround, but not P1 either. Just a Good to Fix.

**Comment by stevejalim** [comment]
Ah yeah, just spotted that

The People page is a template fix.

The Events fix is possibly a data migration and related code change to get the extra in there

**Comment by stevejalim** [comment]
@valgrimm Can you add to the description to clarify (via AC) exactly what needs to change in terms of countries we support + and what labelling needs to change, please?

**Comment by valgrimm** [comment]
AC
Countries support does not need to change
Labelling needs to change for People and Events.

END USER
![people.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/32ec32ed-5341-47d0-9aac-6f20ce77d22a)
![events.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/fdfa9949-7d71-4b99-a39e-9bc28391d6e7)

ADMIN
![people-admin.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/b81a40af-c554-456a-aa72-6373d6574340)
![event-admin.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/37cfe54e-a27e-4253-ac77-37cfc01b069d)

**Comment by valgrimm** [comment]
On Events page Country will likely become Location
