### ISSUE TITLE
Page lag blocks editing

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1195]
What: A page or a post will keep loading and loading interminably when opened, and the "Save"/"Publish"/"Preview" tab will never slide up. The add content sections are all open with the content types unclickable. 

Where: On Stage and Production
Browser: Firefox Nightly and Firefox Release
OS/Hardware: Windows 10 on Lenovo X1 Carbon
Network: Over wifi (with other sites and internet services working just fine)
Using Telenet internet services from home in Belgium (no VPN) and using probably Proximus internet services from a coworking in Belgium (using Mozilla VPN). 
When: Late Wednesday into Thursday and Friday last week, and today Thursday in the afternoon 5 March 2020.
Always on a page I have been editing for a while.
Attempted (failed) solutions: Logging out and back in; closing and restarting browser.

![frozenaddcontentsections.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/5bd0cb12-f696-4b6c-b175-325f5e6c7303)

**Comment by stevejalim** [comment]
Ticketed with Wagtail, but am not 100% sure it's Wagtail's "fault" https://github.com/wagtail/wagtail/issues/5872

**Comment by stevejalim** [comment]
Discussing with @limed too. We're going to see if the suggestions in https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/ can help at all

**Comment by stevejalim** [comment]
Having slept on this, if it IS related to overall page size + our k8s setup then we might be able to replicate it with a single very long rich text area in a page too. Something that takes the payload above 350kb. Will try on Monday

**Comment by stevejalim** [comment]
@valgrimm @limed 

OK, discovered something interesting.

Taking content that makes Stage hang and putting it into Dev:

* Making a ContentPage with the "bad" content does NOT cause things to hang
* Making a Post with the "bad" content DOES cause the page to hang

(DM me if you want the URLs to check for yourself.)

**Comment by stevejalim** [comment]
Downgrading to a P2 because we've got a better approach (ticket to come)

**Comment by stevejalim** [comment]
So, even with the change in #1203 to a simpler page format we can still hit a ceiling.

Going to look at CPU and memory resources in k8s to see if that helps

**Comment by stevejalim** [comment]
We have a promising solution, using `gevent` as the worker for Gunicorn, instead of `Meinheld`. @limed is on the case with a clean changeover to it in k8s

**Comment by stevejalim** [comment]
@valgrimm I thikn @limed has deployed a webserver change that makes this problem go away entirely.

@limed can you confirm? If so, Val can try to replicate on stage (eg trying one of the bad pages) and then we can consider this closed \o/ -- NICE ONE, ED!

**Comment by limed** [comment]
I've deployed the fix on stage and prod. @valgrimm please test and verify if this fix worked. Thanks

**Comment by valgrimm** [comment]
Fixed! Thank you so much.
