### ISSUE TITLE
Show Val how to add more syndication sources

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1198]

**Comment by stevejalim** [comment]
Go to `/django-admin/` 

Click on "Ingestion configurations"

Click on the button to the right hand side to add a new one:
<img width="242" alt="Screenshot 2020-03-06 at 13 31 15" src="https://user-images.githubusercontent.com/101457/76087825-d3c3e380-5fae-11ea-8c1f-fc51c2970ae0.png">

Fill in the details

<img width="743" alt="Screenshot 2020-03-06 at 13 31 19" src="https://user-images.githubusercontent.com/101457/76087846-dcb4b500-5fae-11ea-9efc-ceb4821dd98a.png">

Unless you deliberately want to import older things, click the `Today` and `Now` links to set "now" as the time the last sync occurred, so we don't end up importing things pre-date this point in time

**Comment by stevejalim** [comment]
@valgrimm Does the info above clarify enough for you?

**Comment by valgrimm** [comment]
Yes, this is clear. Thank you!
