### ISSUE TITLE
Update footer to new design

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1222]

**Comment by valgrimm** [comment]
Consider this stakeholder approved as no one complained about anything other than header page last Monday

**Comment by valgrimm** [comment]
Newlsetter signup form is on every page and that was the only question

**Comment by schalkneethling** [comment]
Is the below a bug, or does the layout of the social links still need updating?

![Screenshot 2020-03-27 at 08 49 19](https://user-images.githubusercontent.com/10350960/77729709-fe321b00-7007-11ea-9672-e2d788d576fa.png)

This is on iPad Pro in portrait mode so 1024 x 1366

**Comment by stevejalim** [comment]
@schalkneethling Sorry for the delay on this. I think i'm going to have to live with the footer icon reflow, because there's not a `word-break` CSS option (eg `break-all`) that might help here, I _think_. 

If you have any suggestions, I'm all ears!
