### ISSUE TITLE
Update newsletter signup component to new design

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1224]
- [ ] UI updates
- [ ] JS updates to post to it

**Comment by valgrimm** [comment]
When it is testing time, this behavior is worth investigating

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/18acf715-b11d-4412-9e48-ff0a52bb05a1)

**Comment by valgrimm** [comment]
Consider this stakeholder approved as no one complained about anything other than header page last Monday. All there is blocking completion is that bug
