### ISSUE TITLE
Component design update: Notification Bar

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1231]
Not currently featured in the redesign, but this is how it looks in the design system AND in the current devportal (ie it's standard Protocol CSS): https://protocol.mozilla.org/patterns/molecules/notification-bar.html#

**Comment by stevejalim** [comment]
@malqinneh Heya - do you think we can just continue to use the Notification Bar's default styling? https://protocol.mozilla.org/patterns/molecules/notification-bar.html#

If you want to see it in action, DM me and I'll show you how to trigger it on dev

**Comment by malqinneh** [comment]
My recommendation would be to keep using the Notification Bar's default styling (as indicated in Protocol).

**Comment by stevejalim** [comment]
Sounds good to me @malquinneh!
