### ISSUE TITLE
Design refresh: update placeholder images to new style

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1244]
AC
- [ ] Where an image is in 16:9 aspect ratio, we use a 16:9 placeholder
- [ ] Where an image is in 3:2 aspect ratio, we use a 3:2 placeholder 

Note: we need to check whether we're definitely using 3:2, not 4:3 (easy check)

**Comment by valgrimm** [comment]
I think I did this everywhere on production, did I miss something? @stevejalim
