### ISSUE TITLE
EVENTS: Promote Virtual Events Live on DevPortal

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1253]
March 13 Sandra
Also - is there a way (this is me brainstorming btw) to link events that have now moved to be totally online/virtual on our Devportal sites to cross promote live? for example, perfmatters will be all online. we are a major sponsor

**Comment by stevejalim** [comment]
@valgrimm When you get time, can you add some AC to this so I can work out a rough estimate, please? Happy to discuss on Slack/Zoom if it's easier

**Comment by stevejalim** [comment]
Val has worked this out already, so closing \o/
