### ISSUE TITLE
Design refresh: Single Video page

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1265]
AC
- [ ] Looks sensible
- [ ] HTML valid

**Comment by stevejalim** [comment]
@malqinneh I can't see a mockup of the standalone video page - do you have any recommendations? If not I can just go with somethng sensible myself

**Comment by malqinneh** [comment]
Pushed a mock-up of the video page on Abstract: https://share.goabstract.com/106f93d0-5453-4109-b9a3-2c133d87f618
