### ISSUE TITLE
Design refresh: Events page 

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1266]

**Comment by stevejalim** [comment]
@malqinneh @valgrimm I was just thinking about this page and how we will be switching to adding `Past events` option to the `Dates` section of the filters.

If we wanted to give users a quick way to access past events, we could also use an ad-hoc button that currently appears below the Featured Event but above the listings as a short-cut to enable the 'past events' filter, if you see what I mean

What do you think?

**Comment by valgrimm** [comment]
Note: We current plan to keep functionality from current events page to add buttons above main content as requested by Sandra

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/d623f526-f4df-4117-bbac-fcda8abd7984)
