### ISSUE TITLE
Design Refresh: Individual Topic page 

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1269]
AC
- [ ] Looks like design
- [ ] Support 2..5 featured items
- [ ] Drop tabbed panel 
- [ ] Add "What we're working on" panel (with customisable header text - if time) - 4-up on gray. If there's one item only that still renders as a quarter width
- [ ] HTML valid

**Comment by valgrimm** [comment]
@valgrimm create backups of items in tabbed region on production before release!
