### ISSUE TITLE
Bug for 1224: Newsletter area, illustration shifts

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1290]
Illustration next to newsletter form shifts to the left as one zooms out from page. 
#1224

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/3fd6d738-ccb3-4e57-b6ec-c9563d6cef1c)

**Comment by stevejalim** [comment]
Hi @valgrimm just spent a moment (almost literally) replicating and for me it only starts to reflow badly when zoomed out to 30%. As such, given that it's a cosmetic thing and generally not how people browse (zoomed out is more likely than zoomed in, and even then it's not breaking behaviour), I'd say we don't need to address this as a blocker, and possibly not at all...?

cc @schalkneethling for a point of view, too

**Comment by schalkneethling** [comment]
Will take a look but, perhaps what I have identified here is somewhat related:
https://github.com/mdn/developer-portal/pull/1285#issuecomment-602384862

**Comment by schalkneethling** [comment]
I notice that the class `.newsletter-signup` unsets the `max-width` property.

**Comment by stevejalim** [comment]
This was fixed as part of related tweaks to #1266 

**FF happy at zoomed-out/low magnification**
![Screenshot 2020-03-23 at 15 59 38](https://user-images.githubusercontent.com/101457/77337459-d0f01f00-6d20-11ea-9c94-fb65514a6244.png)

**IE11 now happy**
![Screenshot 2020-03-23 at 15 59 07](https://user-images.githubusercontent.com/101457/77337468-d3eb0f80-6d20-11ea-8f1a-31f1ee60355b.png)

**Mobile viewport still happy**
![Screenshot 2020-03-23 at 16 04 33](https://user-images.githubusercontent.com/101457/77337454-d0578880-6d20-11ea-8b46-954cb2734a6f.png)

@valgrimm If you're happy, can we close this now?

**Comment by valgrimm** [comment]
Yup, that looks good now! Matches Abstract. Bug can be closed.
