### ISSUE TITLE
Use one page template with 5 featured items for homepage and topic page

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1303]
AC
[ ] Topic page featured items area has same card layout as in Abstract design
[ ] Behavior for different numbers of cards (minimum 2 to be consistent) up to 5 is coded
[ ] Eliminate promo items on homepage 
[ ] Eliminate separate homepage template
[ ] Homepage and Topic page use same template minus the 'What we're developing" section on the Topic page

related to #1269
related to #1220
Defer homepage template fix for Late April sprint

**Comment by stevejalim** [comment]
@valgrimm Do you want to extend this to the Events page as well? Would neatly take care of #1300 (drop single event option from Event page), too

**Comment by valgrimm** [comment]
Yes.


(Although I don't want to allow more than two featured events on the events page because otherwise it gets too topheavy, I am maintaining that, I won't add more things. When/if there ar emore/different maintainers we will deal with that problem then).
