### ISSUE TITLE
Addition of GitLab for OAuth.

### ISSUE THREAD

**Issue by mozdevcontrib** [mdn/developer-portal#132]
> Additional organizations can be added via the GITHUB_ORGS env variable.

   Having an alternative OAuth to GitHub - **GitLab** specifically - would be not just nice as well as convenient. It would allow those of us who either emigrated from GitHub due to Microsoft and/or were using GitLab prior to Microsoft's purchasing of GitHub. Being a centralized code hosting platform, GitHub *is* the code it hosts; without it, GitHub would not exist. Essentially Microsoft purchased that code; they control it, including "private" repositories. Closing one's eyes when one owns anything is not the equivalent of not owning said things. This leads to GitLab's core values aligning with Mozilla : both create OSS; compared to Microsoft's use of Closed Source aka Proprietary software for the majority of its products, Mozilla v Microsoft re: core values effectively do not align. I personally *only* returned to use GitHub to login to MDN. Mozilla essentially forces anyone who wants to volunteer to have an account that may be labeled GitHub but is Microsoft. It may function well as a test to know who truly wishes to volunteer; however, that's the only good use I can see.

Edit: A starting point on using GitLab for OAuth for anyone who may wish to better understand just how OAuth functions : https://docs.gitlab.com/ee/integration/oauth_provider.html
The link leads to the Enterprise Edition docs, but it may also be used for people using the Community Edition as well as all who use GitLab.com to host their code.

**Comment by stevejalim** [comment]
Closing, because this seems no longer relevant: Github Auth is no longer in scope for the current iteration of the Developer Portal project and has been removed. (We're only using Mozilla SSO for now.)

Cheers
Steve
