### ISSUE TITLE
Design refresh: confirm unused data fields in Wagtail models

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1331]
Once we're happy that the redesign is accepted, there will be some fields on models (eg Event, Video) that may no longer be needed (eg latitude and longitude). We should clean those up to keep the codebase clean.

PART ONE: 

AC
- [x] Every data model is reviewed for now-redundant fields and confirmed with PO as appropriate.

See #1420 for part two

**Comment by stevejalim** [comment]
cc @valgrimm for awareness

**Comment by stevejalim** [comment]
@valgrimm This was a 3 on the old scale where 3 == 1.5 days. Looking at it now, it's a two-day thing, I think. Splitting it into two one-day things would basically involve creating two separate batches of models to work through, one batch per day. I can do that, if you think it's worth it.

**Comment by valgrimm** [comment]
Yes, please split it.

**Comment by stevejalim** [comment]
@valgrimm Heya (one for Monday) - sat down to split this and decided it's better to discuss a few things with you about whether any features not shown in the redesign but supported in the models are definitely no longer needed (including some unearthed as part of #1233).

So, am splitting this ticket into: 

1) discussion/decision (this ticket)
2) actual removal (a new one)

**Comment by valgrimm** [comment]
Ok, let's discuss in our sync today.

**Comment by stevejalim** [comment]
Done on call with Val :+1: :rocket:
