### ISSUE TITLE
Add auto-formatting and linting

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#135]
Suggestion for autoformatters:
* Python: `black`
* JS: `prettier`   (already in use)
* CSS: `prettier`  (already in use)
* HTML: TBC (or nothing) 

Plus linting and cleanup with:
* `isort` (configuration similar to [this](https://github.com/torchbox/wagtail-torchbox/blob/master/.isort.cfg) to separate out Wagtail imports)
* `flake8`
* `eslint` (already in codebase)

All of this driven by ~[pre-commit](https://pre-commit.com/)~ [therapist](https://github.com/rehandalal/therapist)

**Comment by escattone** [comment]
@stevejalim Love it! We're planning to use `black` on kuma (but just haven't done it yet) and already use `prettier`. We're using `flake8-import-order` for enforcing import order on kuma, but after looking at `isort`, I like it much better!

**Comment by stevejalim** [comment]
Great, I'll give it a whirl! Thanks for the 👍

**Comment by escattone** [comment]
@stevejalim Also, I've never used `pre-commit`, but we were thinking about using `therapist` on kuma. Do you have any thoughts on `pre-commit` vs. `therapist`?

**Comment by stevejalim** [comment]
I've not used therapist but will take a look and compare - cheers!

**Comment by stevejalim** [comment]
@escattone Took a look at `therapist` (aided by what looks like a draft ADR [gist](https://gist.github.com/peterbe/ddbc5bd35812247237fb24e049426796) from @peterbe 😄 and the [PR about it in main mdn](https://github.com/mdn/mdn/pull/72.).) 

Deliberately leaving aside the existing leaning towards `therapist`, I think the lack of a need for a virtualenv and the cleaner config syntax puts it ahead, so happy to go that way. Will give it a shot.

**Comment by stevejalim** [comment]
By the way, re: `isort`, I remembered a decent Wagtail-friendly example of custom module, from the lovely home of Wagtail:

https://github.com/torchbox/wagtail-torchbox/blob/master/.isort.cfg 

Will use that as the basis/starting point for ours, basically replacing `tbx` with `developerportal`.

There is a risk that custom isort configs can get missed if a code editor's isort plugin doesn't by default pick up the .isort.cfg from the project dir, so you get an import tug-of-war between the editor and your CLI linter. 
We'll see - it might just be solved by documenting that one's editor might need more explicit configuration to find the right config file.
