### ISSUE TITLE
Fix up runtime patching of Page model, which is creating a wagtailcore migration

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#136]
## Current state

The folllowing code currently patches the help text of all Page models (and their subclasses). 

https://github.com/mdn/developer-portal/blob/307e216c27efa3a0047f7eaedbc2dffaae6297d0/developerportal/apps/common/wagtail_hooks.py#L28-L43

However, I _think..._ this runtime patching means that when `manage.py makemigrations` is run without specifying an `app_label`, it checks the (runtime-patched) state of core Wagtail's `Page` model, which creates a new migration. Migrations shoudn't be added for Wagtail itself, only our app code. 

If generated and applied, this migration would cause a migration conflict when upgrading to a newer version of Wagtail, so is best avoided altogether. 

## Suggested solution

A workaround in documentation ("Watch out for X") probably isn't robust enough, I think.
Cleaner is to remove the runtime patching and replace with a different approach: 
* add a `BasePage` subclass of `Page`, from which all other project pages inherit, and add the various label/help-text updates there. These can then be reflected in migrations that live in `developerportal/apps/*`

**Comment by stevejalim** [comment]
Picking this up now

**Comment by stevejalim** [comment]
Hmm, so this is more fiddly than it first seemed. Posting a note here partly for me but also in case @dcgauld can shed any light (or point out if this is not a valid ticket)

As mentioned, there's runtime patching of the `Page` model which updates `help_text` with a value from a `Site` object (if it exists). This _appeared_ to have the downside of creating a bogus migration for `wagtailcore` if `makemigrations` was run (ie, it made a migration to change the help_text on `wagtail.core.Page`) and I _assumed_ (above) that it was because of the runtime patching of `Page` directly, (via `wagtail_hooks.py`) 

So, I took out the patching and confirmed that it no longer created the bogus wagtailcore migration. Yay.

But then I tried to move that patching logic to a new `BasePage` class and override the relevant field's `help_text` in the `__init__` to splice it in there. Guess what? That bogus wagtailcore migration started to be created again(!)

I tried switching from a subclass of `Page` to a simple mixin class and it still didn't stop the bogus migration being created.

So there's possibly something about the way `Page` works that means that if a field's spec is mutated, it also affects the `Page` superclass. That's the only explanation I can think of right now, but would welcome thoughts!

**Comment by stevejalim** [comment]
(I don't want this to become a yak-shave, so it might just be the simplest fix is to document it as a known niggle and simply say "never run `manage.py makemigrations` without an app name" 😄

**Comment by liamnewmarch** [comment]
Hi @stevejalim 👋  I’m on the team at Potato and I’m afraid I’m responsible for the headache you’ve been having today. Sorry about that!

I ran into similar problems as you subclassing `Page` as well. It looks like the inability to change those fields is a limitation of Wagtail.

Saying that, I was able to change the label of the `title` field on the `Person` model from __"Title"__ to __"Full name"__ by [overriding the `FieldPanel`][1].

Maybe having a `BasePage` subclass/mixin which overrides the `FieldPanel` for all our models would work?

[1]: https://github.com/mdn/developer-portal/blob/master/developerportal/apps/people/edit_handlers.py

**Comment by stevejalim** [comment]
Heya @liamnewmarch 👋 - no worries at all! I've asked in the Wagtail slack, to confirm I'm not losing grip on reality, but I like your suggestion about the `FieldPanel` - will give that a swing!
