### ISSUE TITLE
[DEV] Event pages without an image return Internal Server Error

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1361]
I seem to have found a bug in the Events page on dev. When you click on an event without an image you are sent to a page saying nothing but "Internal Server Error". The same happened when I went in from the Admin side (where the page does exist, yes) and tried to view the page live and also got "Internal Server Error"

**Comment by valgrimm** [comment]
Example: https://developer-portal.dev.mdn.mozit.cloud/events/rusttokyo/

**Comment by stevejalim** [comment]
Fixed! Thanks for the prompt heads-up!
