### ISSUE TITLE
Remove/Replace Github auth flow for Wagtail admin

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#138]
Some Github-related authentication appears to be in place, but it sounds like we're looking elsewhere for an auth backend to use.

- [ ] Get confirmation of what auth backend (Mozilla LDAP?) we'll be using
- [ ] Remove Github auth
  - [ ] See if we can remove python-social-auth (depends on what auth backend we end up choosing)
     - [ ] check if there is any data on staging re social-auth
         - [ ] If so, write careful migration to purge it
     - [ ] Write data migration to drop social-auth tables (will have to be in `apps/common` and handle the non-existence of the tables gracefully)
[ ] Add new auth support instead

**Comment by stevejalim** [comment]
Going to remove this for now

**Comment by tobinmori** [comment]
@atopal can we get confirmation on the planned auth workflow for Wagtail admins? (Github auth vs. LDAP)

**Comment by atopal** [comment]
I don't have an answer for this at this point.

**Comment by stevejalim** [comment]
Related: #401 - if we haven't removed GH auth yet, then doing this will be a subset of the work in #401

**Comment by stevejalim** [comment]
This is handled as part of #401 so closing now
