### ISSUE TITLE
Check/fix automatic, post-publish static build

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#139]
Currently, there are handler for the `published` and `unpublised` Signals, which then trigger a new `subprocess.Process` to build the static site.

Unforunately, they don't appear to be working locally because the DB becomes unavailable:

```
app_1     | INFO:developerportal.apps.staticbuild.wagtail_hooks:Static build task ‘Build’ started.
app_1     | INFO:bakery.management.commands.build:Build started
app_1     | Process Process-1:
app_1     | Traceback (most recent call last):
app_1     |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
app_1     |     return self.cursor.execute(sql, params)
app_1     | psycopg2.OperationalError: server closed the connection unexpectedly
app_1     | 	This probably means the server terminated abnormally
app_1     | 	before or while processing the request.`
```

- [ ] tail the postgres logs when it happens - is there something schema-related that's killing the DB?
- [ ] consider moving to a different approach (eg task queue with `celery`/`django-rq`) if `Process` can't be made to reliably work

(Note that building the site via management command from the CLI seems to work fine)

**Comment by stevejalim** [comment]
Heya @dcgauld - before I rummage in this, is there any chance you can replicate (or hopefully, contradict!) my experience trying to trigger an automatic post-Publish build? 

I basically set `DEBUG=False` in a `settings/local.py` file and published a page, which meant the static build is triggered (https://github.com/mdn/developer-portal/blob/master/developerportal/apps/staticbuild/wagtail_hooks.py#L26)

**Comment by dcgauld** [comment]
Hey @stevejalim, yeah I can reliably replicate this locally too.

**Comment by stevejalim** [comment]
Ok, will move this to a task queue, no worries.

**Comment by stevejalim** [comment]
Working! - Big up thanks to @limed!
