### ISSUE TITLE
Make go-live plan

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1408]
Including list of content changes required to support new design

AC:
- [X] Any component in the new design that will not 'just work' with the existing content in production should be flagged so that appropriate new content can be updated - [GAP ANALYSIS DOC HERE](https://docs.google.com/document/d/1tLV3A5q6WmnmR850B6Dopgs-n7k34rPqLfoK0A6dx6s/edit#)

- [ ] We have a workable plan for deployment of code and updating of content, minimising production downtime --> [PLAN DOC IS HERE](https://docs.google.com/document/d/1pfqm7kA9zsx4zJ1Y_EvRr0M2BoQFUAwXQ5_ya1TYi5s/edit#)

**Comment by stevejalim** [comment]
Some things I've noticed so far:

- [ ] People images all need sorting out again because crop and aspect-ratio has changed from a circle to a 16:9 landscape image
- [ ] Event images all need checking - some fit fine with auto-cropping to 16:9, others do not
- [ ] Any pages with a Featured section need to have at least two items specified so that the new design will not break when we go live with it. 
- [ ] The Events page will not be able to support two featured events until we deploy the redesign (or we add code specifically to the master branch to support two featuring features in production now, but only show one in the old design)

**Comment by valgrimm** [comment]
@stevejalim 

Proposal for redesign rollout:
Val: Moves content waiting for approval from Stage to Dev, Dev becomes the place where content waiting for approval lives. (Will be doing this today, 12 May)
Steve: Apply redesign to Stage
Steve: Copy Production onto Stage
Val: Edit content on Stage to fit redesign
Steve: Push update from Stage to Production, so proper content is deployed along with redesign

Sound workable

**Comment by valgrimm** [comment]
Also on events page that sounds fine.

**Comment by stevejalim** [comment]
@valgrimm will think this through and get back to you. Moving content between environments is fiddly because it's also moving assets not just database snapshots (which both need @limed to be available).

**Comment by stevejalim** [comment]
@valgrimm Assuming that @limed can shuffle content between environments for us - and at a time that suits us - that generally sounds like it should work, thanks! 

I've extended it with more detail in [this doc](https://docs.google.com/document/d/1pfqm7kA9zsx4zJ1Y_EvRr0M2BoQFUAwXQ5_ya1TYi5s/edit?usp=sharing) which will be easier than planning in comments
