### ISSUE TITLE
Design refresh: support automatic 'letterboxing' of images which do not match appropriate aspect ratio

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1439]
For some cases, we have an image that does not fit the fixed 16:9 or 3:2 aspect ratio of images in the new design.

For example:

![Screenshot 2020-05-06 at 10.53.53.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/73834f31-70ee-4d5b-84f3-a469b6998175)

As a way to mitigate this, and give us either a reasonable default/fallback, and as a way of identifying incorrect-ratio images, we will add a new Wagtail image-processing operation that will, where needed, create a composite image that effectively puts coloured bars above and below a short image, or left and right of a narrow image, bringing the overall image up to the appropriate aspect ratio.

eg:

![Screenshot 2020-05-06 at 10.55.07.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/a38ed073-489b-4cbf-a12e-4045962bcb19)

AC
- [ ] Images have no bars if they are exactly the aspect-ratio they are meant to be used at (ie 16:9 or 3:2, especially if #1438 is done first)
- [ ] Images that are too "short" in aspect ratio (eg 16:4) are vertically centered on an image of the correct aspect ratio (and required size), giving the impression they have coloured bars above and below
- [ ] Images that are too "narrow" in aspect ratio (eg 10:9) are horizontally centered on an image of the correct aspect ratio (and required size), giving the impression they have coloured bars to the left and to the right

TO BE DECIDED:
- [ ] Do we use a particular colour consistently? If so, which?
- [ ] Alternatively, shall we use the same backgrounds as the relevant placeholder images? ie:
![Screenshot 2020-05-06 at 12.08.45.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/81bbe58e-8abc-4af7-8d07-666faf21a796)
![Screenshot 2020-05-06 at 12.09.02.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/022dfe98-b067-490d-a5fd-a919db83ff90)

**Comment by stevejalim** [comment]
@valgrimm Could you take a look at this, including the proposed AC, and also the TBC parts - would welcome your view

**Comment by stevejalim** [comment]
@valgrimm Could you take a look at this one, too, please? If you see "Error rendering Markdown" please can you view it [in Github](https://github.com/mdn/developer-portal/issues/1439)) not Zenhub?

**Comment by valgrimm** [comment]
This sounds good to me. Also, I'd make the colored bars black. Gray is too obviously an error and white may blend in.

**Comment by stevejalim** [comment]
Parking this - spent a bit of time on it but it needs more and we can live without it
