### ISSUE TITLE
Whole-site search: A search field should be present in the main site navigation

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1453]
AC

**In general:**
- [ ] Search input is a regular text input
- [ ] ~Search input is followed by a button to the right of the field. This button contains a magnifying glass icon.~
- [ ] ~Clicking the magnifying glass buton will trigger a search~
- [ ] Hitting enter when focused in the search input will trigger a search

**On desktop/medium breakpoints:**
  - [ ] The search input + trigger button appears at right end of navigation 
  - [ ] Nav reflows gracefully as the uncollapsed version of the nav is squashed narrower due to narrower viewports

**On mobile breakpoint (ie, whenever the navigation is collapsed by default:**
  - [ ] The search input appears as the last element in the stack of options (ie below "About" in the current site

**Comment by stevejalim** [comment]
Heya @valgrimm This is what the default Search box should/would look like if we stick with Mozilla Protocol's design - note the magnifying glass is on the inner-left not the right of the input:

![image.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/c4b7f729-5280-4689-902e-3dad8193e2dc)

**Comment by stevejalim** [comment]
Have added some AC for mobile, too

**Comment by stevejalim** [comment]
Estimating this as a day because I suspect we'll have to work quite hard to make the search input fit in to (or reflow within) the nav as the viewport gets narrower
