### ISSUE TITLE
Investigate spacing difference between links created within a rich text field vs buttons

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1462]
The amount of space between buttons varies. If created in a rich text field there is a huge space between them. If created as normal buttons spacing looks more normal. Solution short term is not to use buttons in rich text field, which is fine. 

![weirdspacingbuttons-2.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/abfa961b-4de2-40f9-a696-cb7497d58a8d)

![weirdspacingbuttons-1.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/d5b7b73e-cac7-45d8-879d-ea9480b4cd7a)

**Comment by stevejalim** [comment]
@valgrimm I think if you put them in side the same button block (the same dotted line around it) they should not have that epically large amount of space around it. Takes a little but of copy-paste and cursor-tapping to move a button link into the dotted block with another one (and maybe soft return/shift+return to knock it on to another line). 

Does that work?

**Comment by stevejalim** [comment]
@valgrimm yeah it's the soft-return (`shift`+`return`) that is key to keeping the links within that dotted box:

![Screenshot 2020-05-12 at 14 51 33](https://user-images.githubusercontent.com/101457/81700124-2b277980-9460-11ea-9959-cdaf1073bef5.png)
![Screenshot 2020-05-12 at 14 51 37](https://user-images.githubusercontent.com/101457/81700132-2c58a680-9460-11ea-866c-abedea589f34.png)

**Comment by valgrimm** [comment]
👍
