### ISSUE TITLE
Whole-site search: Allow indexing of CMS content

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1469]
AC

For each of the following page/content types

- [x] `Event`s
- [x] Posts (`Article`s) 
- [ ] `Video`s
- [x] External Posts (`ExternalArticle`s)
- [x] `ExternalVideo`s
- [x] `ExternalEvent`s
- [x] `Topic`

The following fields must be indexed by Wagtail:
- [x] Title
- [x] Description
- [x] Topic tag(s), if relevant

Plus for Video pages: 
- [x] index the `body` field, which is used for descriptive content that accompanies a video

- [x] Until a search results page is implemented, proof of this behaviour can be achevied via Python unit tests

NOTE:
- We'll have to update existing calls to search() for Posts, Events and People to add in specific field constraints so that those pages don't search on any other fields we start indexing, which could be less relevant

**Comment by stevejalim** [comment]
@valgrimm I've spun up this ticket as a child of the Epic. Let me know if the AC work for you

**Comment by valgrimm** [comment]
I'd argue that content pages are also CMS content . . . but I see what you're doing here, it makes sense. I think I'll need a quick explainer on Slack or in our meeting about what you mean here with "proof of this behaviour can be achevied via Python unit tests".
