### ISSUE TITLE
Visitor should be able to search through all content on Topic page and subpages

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1470]

**Comment by stevejalim** [comment]
@valgrimm Before I can break this user story down a bit more, can you clarify what "all content" here is referring to, for you? Top-level Topic pages hold no unique content of their own - they simply act as a 'pin board' for other pages in the site (and some external links).

I can appreciate that Topic pages may have child Content Pages that have related content, in a tree or in a parent -> child -> child -> chain. All of the content in those content pages can be indexed and can show up in search results. What might be quite tricky is uniquely associating those pages with a specific parent topic -- though am not sure if that would be strictly necessary (and probably not at all for the first/MVP approach to Search?)

**Comment by valgrimm** [comment]
Topic pages have a description, actually, so I'd like folks to be able to search that.
The child Content pages don't need to be associated with a specific topic, no, not in this MVP of search.

**Comment by stevejalim** [comment]
Closing this ticket as it's overlapping nicely what is happening in #1469. `Topic`s will get their `description` field indexed, no worries.
