### ISSUE TITLE
Whole-site search: search results page

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1471]
User story: As a Visitor I should be able to view results on default Wagtail search results page

## Aceptance Criteria

- [X] A standalone search-results page exists within the CMS that shows search results
- [X] The page is rendered by a custom Django/Wagtail view, based initially on a simple Search approach.
- [ ] The styling suits the look and feel of the rest of the developer portal (eg, it could use Cards to represent search results in a similar way to the Posts and Events pages)

- [ ] The search-results page should show its own search input, so that the user can refine their search parameters
- [ ] There will be no option to select tags/topics via check-boxes or similar - all search params are entered via the Search text input

- [ ] The search-results page should show a linear list of results from wagtail searching based on the parameters entered via the main Search box in the nav (or the Search box in the Search Results page)
 
- [ ] Each result will comprise, simply:
  - [ ] The title of the page/entity that has been returned as a result, rendered as a hyperlink to the entity 
  - [ ] The first 120 characters of any description associated with that page/entity
- [ ] The search-results page will be paginated to 15 results per page.
- [ ] The search-results page will show how many results there are overall and how many pages remain to be explored.
- [ ] The search-results page should work via the CDN

## Stretch Goals 

Must be split into own cards if we want them - _not included in the estimate_

- [ ] The search results will be grouped by the page type they refer to. Specifically:
    - [ ] Posts (including internal and external Articles and Videos)
    - [ ] Topics (ie, any content pages that are childrent of specific Topics, including the Topic page itself)
    - [ ] Events
    - [ ] People

- [ ] "Promoted" results should appear at the top of the results list even if they otherwise rank lower

**Comment by stevejalim** [comment]
Heya @valgrimm - have had a swing at initial AC/breakdown for this ticket. I've put a rough estimate on it and if you're happy with the AC can chop it down into day-size tickets if need be

**Comment by valgrimm** [comment]
I like the AC, looks great! If you're prioritizing stretch goals at all grouping search results by page type would be my favorite.

**Comment by stevejalim** [comment]
@valgrimm 

> If you're prioritizing stretch goals at all grouping search results by page type would be my favorite. 

I agree, and it might actually be simpler/less effort to do the grouping as the default behaviour, so am happy to go with that as the standard results page

**Comment by stevejalim** [comment]
Ah, wait: grouping doesn't play well with pagination, so let's go with straightforward results for now
