### ISSUE TITLE
External page links do not draw on card images in "current work" section of Topic pages

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1497]
When an external page link is added to the "What we're working in" / "What we're developing" part of a Topic page, the card images selected for it do not load.

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/a7b3d8d9-af4e-4e53-9bc0-9797273cd421)

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/5c92ce4e-9d48-417f-9059-491f54506374)

**Comment by stevejalim** [comment]
Fixed
