### ISSUE TITLE
Events page: Date ordering odd 

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1523]
Events appear in the list in a strange order that does not seem to match their dates. 
Observed on Production. 

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/fc836041-7899-4cb2-a060-59a00a84bcca)

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/c91f4c54-3920-4500-8979-c47e652dfbc0)

**Comment by stevejalim** [comment]
Hi @valgrimm - the ordering looks like it's reverse chronological, flowing left to right per line. What were you thinking it would be, please?

**Comment by stevejalim** [comment]
We could do something "smarter" - eg: the default view is events that are happening in the next N months (eg next 6 mths?) and drop the future dates and replace it with 'future events'

Then we'd be left with something like this:

![Screenshot 2020-06-02 at 11.28.24.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/9e298c21-86ed-4cfa-9043-1ff74df596f9)

Just an idea - would definitely need some thinking/bouncing around before making the change

**Comment by valgrimm** [comment]
Hi Steve, I like your idea about showing the next six months. When folks arrive on the page they should see the events coming up soon, not ones far in the future.

**Comment by valgrimm** [comment]
I would prioritize this over search, if it is a quick fix. Sandra will care.
