### ISSUE TITLE
Event page search: enable indexing for all models which appear on the Events page

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1534]
- `Event`
- `ExternalEvent`

**Comment by valgrimm** [comment]
Same AC as #1510, but for Events

**Comment by stevejalim** [comment]
@valgrimm For now I'm going to index

`Event` -> `title`, `description` and `body` fields
`ExternalEvent` -> `title` and `description`

Do you think it's worth (currently) indexing based on the names of the associated speakers, too? It's a small change in terms of code, but a larger change in terms of the results we might get back. Maybe better split out into a follow-up card for later in the summer?

**Comment by valgrimm** [comment]
I'd split speaker names into a follow-up card, feel free to write and then I can discuss with Sandra. I think that is a post-launch type feature.
Generally this sounds good otherwise.
Re ExternalEvent, I'm not sure what this is, but the rest sounds good. 
Thanks for highlighting this.

**Comment by stevejalim** [comment]
> I'd split speaker names into a follow-up card, feel free to write and then I can discuss with Sandra. I think that is a post-launch type feature.

👍 

> Re `ExternalEvent`, I'm not sure what this is, but the rest sounds good.

Much like we can have `ExternalArticle` or `ExternalVideo` that are just links off to external sites with no content other than cards rendered in the site, we can do the same with Events, if we wanted to link to one but show no other content about them in the portal

**Comment by valgrimm** [comment]
super. thank you!
