### ISSUE TITLE
Production server: Event detail page / "Official event site" button redirects incorrectly 

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1537]
When user clicks "Official event site" button, they are returned a bogus redirect. 

Issue identified with 
IndieWebCamp West Coast
https://developer-portal.prod.mdn.mozit.cloud/admin/pages/412

Issue replicated with
Game Devs of Color Expo 2020
https://developer-portal.prod.mdn.mozit.cloud/admin/pages/504

Not an issue for most events that just have register links.
Workaround exists. 

Website address
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/d1aad1ec-f5dc-4b57-9097-136c283011e6)

Data entered in Wagtail admin
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/f2ebcc0e-b27b-46e9-b6fa-bf67aa1b0620)

Result of clicking "Official website" button
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/6cb5a083-ea35-47f2-acdd-e9fbdf8befd6)

Workaround:
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/ccc5c2de-d5a9-42f7-ae05-aa2e34be3995)

**Comment by stevejalim** [comment]
Fixed in 9de9fef9e1a
