### ISSUE TITLE
Test replacement for main page hero image on dev

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1551]
![homepagehero_v2_large](https://user-images.githubusercontent.com/56933147/84158863-a46cb900-aa6c-11ea-95db-404f287cbd97.png)
homepagehero_v2_large

**Comment by stevejalim** [comment]
@valgrimm do we have a lower-resolution `@1x` version available too, please?

**Comment by valgrimm** [comment]
I'm not sure I understand, can you clarify? This is based on downloading and clearing out and replacing the image from the current homepage hero. I assume there are different versions for responsive design or something?

**Comment by stevejalim** [comment]
Yeah there's a high-res version (which is usually labelled `@2x`) which appears to be the one uploaded in the main description. If we have a lower-res version available, I can use that -- or I can make my own lower-res one, no worries

**Comment by stevejalim** [comment]
Actually, maybe it's not higher-res. Will see how it looks on stage, soon!
