### ISSUE TITLE
Replace AWS Access Keys with Roles

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#1578]
Since AWS has released IRSA (read more about it here https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) it treats pods as first class citizen's in the eyes of IAM

So we can now have the pods assume a role instead of importing the environment variable into the pod. We do this by creating a service account and annotating it with a special annotation. Once we thats done we references the serviceAccount in our pod, deployments etc etc

We have a few  places where we still have IAM access keys exported into the environments so we need to go around and find them and replace them with roles

**Comment by stevejalim** [comment]
@limed Any idea how we'll make this work with local dev for S3 and CloudFront access, too?

**Comment by stevejalim** [comment]
From our slack chat, I guess we need to plan a time to:
a) add the new way as env vars (@limed)
b) switch to using them in code (@stevejalim)
c) drop the old way from env vars (@limed)

We'll need a local-dev role creating too

**Comment by stevejalim** [comment]
@limed for the record, was this completed or still stuff to do?

**Comment by limed** [comment]
Wasn't finished and all a bit too late at this point
