### ISSUE TITLE
Events page needs a header above the main events list to aid user navigation

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1594]
The Events page differs from Posts and People because it had rich text above the list of cards. As such, particularly on mobile, the page can be confusing to understand.

To fix this we could add a subhead above the lost of even cards, probably only visible at the smallest viewport width (mobile)
```

**Comment by stevejalim** [comment]
@valgrimm one for a chat on Monday

**Comment by stevejalim** [comment]
Handling this as a one-line change in #1539

**Comment by valgrimm** [comment]
Let's discuss before applying any changes.

**Comment by stevejalim** [comment]
Well, it's now rolled in to https://github.com/mdn/developer-portal/pull/1600 because it was a v small change and made the UX of feature delivered in that PR much better, too, so hopefully you'll like it, too. It only appears on the Events page and then only on mobile viewports
