### ISSUE TITLE
As a site maintainer, I want to present Topics to visitors by importance (not title)

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1598]
@malqinneh:  How might we best highlight pages by importance without harming the user experience?
( @stevejalim: fyi, to participate in discussion )

Situation description:
- Right now Products & Technologies are listed in alphabetical order in the dropdown menu and the topics "module" at the bottom of the homepage. This makes sense. 
- However, it also means that the newly introduced Web Compatibility section is hidden way down in the Products & Technologies list in the dropdown menu. 
- As it is a topic very relevant to developers, I would like to highlight Web Compatibility as one of the first things visitors would see. 
- If we are moving things, it would also be preferable to have visitors see the Firefox and DevTools pages earlier in the navigation and homepage module than they do now.
- AV1 and video (later to be retitled to Open Media if I can get the ok) and Rust, which currently appear at the top of the menu, are not the most important topics to highlight.

**Comment by stevejalim** [comment]
A common pattern is "promoted results" where some items are at the top and get a slightly different visual treatment.

In our case, we could put the item on a tinted panel/card or similar (via a tickbox we could add to enable this)

Also at the moment we should already be able to arbitrarily order topics in the menu via drag ordering in the CMS. If this isn't the case (eg it wasn't enabled) I can enable that too

**Comment by valgrimm** [comment]
Thank you Steve! I like your solutions, but want to just get some input from Mustafa before we make a decision, as this is pretty significant user experience element.

**Comment by stevejalim** [comment]
@valgrimm No worries!

Just checked and it is possible to use manual ordering for the Topics, but it's not obvious that it's possible, tbh.

On the Topics page, you need to click the "sort" link to enable manual ordering and show the drag handles to put pages in a custom order. See https://docs.wagtail.io/en/stable/editor_manual/finding_your_way_around/the_explorer_page.html#reordering-pages

Here's an example of me having done it locally (with local topics):

<img width="451" alt="Screenshot 2020-06-22 at 09 40 29" src="https://user-images.githubusercontent.com/101457/85266929-7758d700-b46c-11ea-9c7d-f3d91e13c571.png">
<img width="1188" alt="Screenshot 2020-06-22 at 09 40 38" src="https://user-images.githubusercontent.com/101457/85266943-79229a80-b46c-11ea-85fb-c710875d5848.png">

(The CDN will need invalidating on prod after the chages are made, which can be most easily done by re-publishing a live page with no changes)

**Comment by stevejalim** [comment]
I also just recalled that Mozilla Protocol (the design system we're built on) does not have any styling for 'featured items' so we'd either have to:
1) invent it ourselves (and maybe contribute it back to Protocol)
or 2) use an existing cue that it does suggest, which is to have a coloured icon for certain things (see https://protocol.mozilla.org/demos/navigation.html) - which we could support alongside the default topic icon for a Topic, showing this custom icon in the menu when it's marked for 'promotion'

**Comment by valgrimm** [comment]
@stevejalim thank you for the investigation and info! : D

**Comment by malqinneh** [comment]
@valgrimm 

There might be a few options for us to consider here. But my first suggestion would be to propose a 'new' tag (see example of image(s) below):
![purple](https://user-images.githubusercontent.com/4819906/85304109-5e0a5780-b479-11ea-8596-f11bf85eb5be.png)
![blue](https://user-images.githubusercontent.com/4819906/85304125-62367500-b479-11ea-8f89-22bf009dd288.png)

**Comment by valgrimm** [comment]
@malqinneh I like the "new" tag, and would like to add that too--but nope, it doesn't address the issue, sadly.

The key pages I am thinking of will remain important even when they are no longer new/most recently updated--_Firefox_, _DevTools_, _Web Compatibility_, and later _Security & Privacy_ and _Mobile Development_ as well. 

What we need is a way to make them the most prominent and easy-to-access pages in the Products & Technologies menu, but while keeping the other products and technologies in a useful (possibly still alphabetical) order.

**Comment by malqinneh** [comment]
> most prominent and easy-to-access pages

Ie. sorting products and technologies (on the landing page and dropdown) by org importance?

If so, that works! I'd recommend keeping an eye on how often we're having to reprioritize the menu compared to how many visitors are recurring (so that we can avoid switching menu items on recurring visitors).

> while keeping the other products and technologies in a useful (possibly still alphabetical) order

With the number of products and technologies we're displaying - I think it's either we sort them by [importance] or [alphabetical]. Basically, we're thinking of prioritizing almost 50% of our products and technologies (by org importance) and the remaining 50% alphabetically (confusing). Why not just organize all products and technologies by org importance?

**Comment by valgrimm** [comment]
> Ie. sorting products and technologies (on the landing page and dropdown) by org importance?

Yup.

> If so, that works! I'd recommend keeping an eye on how often we're having to reprioritize the menu compared to how many visitors are recurring (so that we can avoid switching menu items on recurring visitors).

I'd just want to prioritize it once, although we'll be adding some more sections in the next months . . . . what's the least disruptive way to approach that? They'll just push that is already there downward. Nothing would bubble up. 


> With the number of products and technologies we're displaying - I think it's either we sort them by [importance] or [alphabetical]. Basically, we're thinking of prioritizing almost 50% of our products and technologies (by org importance) and the remaining 50% alphabetically (confusing). Why not just organize all products and technologies by org importance?

Ok, so sorting them all by importance is ok? I was nervous about moving away from alphabetical, but if it is all one or all the other, I'm good with that. Cool. 

Ok, so it sounds like the best thing to do is to just organize by priority, and I have a plan for adding new topic areas as well. 

Thanks Mustafa!

**Comment by valgrimm** [comment]
Ok, so the visuals will remain the same and I will just manually reorder stuff. Closing this ticket. Thanks everyone!

**Comment by valgrimm** [comment]
**Change request**

Submitted by: Val G
**Change summary**
Reorder the navigation menu of the Dev Portal by priority rather than alphabetically.

_Current list (from top of menu)_
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/7cd36897-e21b-4b19-a3ba-d4ce9659296e)

_New order_
Web Compatibility - Security & Privacy (when it is ready)
Mobile Development (when it is ready) - Firefox
Developer Tools - AddOns
Mixed Reality - Voice
Open Media Formats - WebAssembly
Rust - WebThings

**RACI**
Responsible (makes final decision): @chrisdavidmills 
Accountable: Val G, Steve J
Consulted: Sandra Persing @havi @callahad  @atopal 
_Note: R and A people need to provide feedback. C and I people’s feedback is optional_

**Due date for responses to this proposed change**
5pm Pacific Standard Time July 3

**What is the proposed date for the change to be made?**
Once approval is granted, if it is. 

**Why are we making this change?**
To prioritize topics responding to MDN DNA input.
To support organizational priorities and developer interest.

Please provide feedback in comments below.

**Comment by chrisdavidmills** [comment]
The new order looks reasonable to me, per se, but I have noted that some pretty major topic areas are left off the new list. I'm not so fussed about AV1 video, as a lot of web developers won't be particularly fussed about getting lots of information on the internal workings of a video codec.

But CSS and JavaScript? These are subjects of central importance, surely? How will developers get to these topics if they are removed from the menu?

**Comment by valgrimm** [comment]
> not so fussed about AV1 video

Regarding AV1, I've proposed to Nathan and David that it be relabeled to open media formats as AVIF is not video and has a different name than AV1, but is related. I intend to follow up on this. 

> But CSS and JavaScript?

I was planning to make a separate ticket regarding this. I have. It is #1611.

**Comment by chrisdavidmills** [comment]
> I was planning to make a separate ticket regarding this. I have. It is #1611.

Right ok, makes sense now.

So I think I'd be OK with testing out this change, but I still have a gut feeling that it might be a bit odd to come to a web development site and not be able to find pages about HTML, CSS, or JavaScript.

This is worth looking at in user testing. I also wonder if in the future it might be worth having these topics listed under a title along the lines of "Core Topics", and then also have a heading of "Technologies", which when clicked just brings you to lists of article tagged with those technologies?

But for now, I'm OK with this.

**Comment by valgrimm** [comment]
Chris has okayed and there have been no other comments even though I extended the comment period, so this is going ahead. Just unpublishing JavaScri[t and CSS pages, not deleting.

**Comment by valgrimm** [comment]
related to #1611

**Comment by valgrimm** [comment]
Done
