### ISSUE TITLE
Add a streamfield below event listing

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1603]
A pointer to the community portal and information about getting event sponsorship are most appropriately located below the event listings, especially as sponsorship is being deemphasized.

AC:
- [ ] A streamfield below the event listings that can support two rich text fields and two buttons.

**Comment by stevejalim** [comment]
@valgrimm This is for the Events page, not on an individual Event page, yep?

**Comment by valgrimm** [comment]
@sandrapersing for review

**Comment by sandrapersing** [comment]
looks good

**Comment by valgrimm** [comment]
ok @stevejalim, good to deploy this one
