### ISSUE TITLE
Marker for cards for events sponsored by Mozilla DevRel

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1604]
Sandra wanted to make it clearer which events we list are sponsored by Mozilla Developer Relations.
A visual marker would meet this need.

AC: The marker should be visible from the events list and the events detail page. 

@malqinneh How might we best mark an event in the events list and an event on the event detail page? It would be ideal to include the phrase "This event is sponsored by Mozilla Developer Relations" on at least the event detail page. 

( @stevejalim for input)

**Comment by stevejalim** [comment]
Pending anything better we get from @malqinneh of course, here's a shot at something that could work. 

![Screenshot 2020-06-23 at 13.01.11.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/ffe38b66-a6c5-4937-85ec-d6f01fd87d6c)

![Screenshot 2020-06-23 at 13.02.43.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/6a60c44f-651c-4522-b160-497b56669fff)

We could make the content of the label (and the background colour of the pill) customisable via the Meta tab when editing the relevant Event. (Or, if it customisation isn't needed, just add a 'Mozilla supported' checkbox to that Meta tab -- we'd also need a decision on what the best wording would be)

**Comment by stevejalim** [comment]
Ballparking this as 1pt for now

**Comment by malqinneh** [comment]
Looks good Steve! I would propose "Backed by Mozilla" or "Sponsored by Mozilla"

"Backed" is 6 characters, "Sponsored" is 9. If adding 3 more characters isn't too long, I'd opt for that since it's clear/direct.

**Comment by valgrimm** [comment]
I agree on "Sponsored". Especially relevant for non-native speakers of English. Otherwise, this looks great! Kudos. 👍

**Comment by stevejalim** [comment]
Turns out that injecting the blue label into the header is a bit of a rabbit-hole, so before I do that, I thought I'd float what now happens given we show the blue label on the event card:

![Screenshot 2020-06-29 at 21.46.35.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/7869a362-f90b-469c-a5a6-22a46a6abf15)

@malqinneh @valgrimm Do you think having it marked in the card alone is enough?

**Comment by stevejalim** [comment]
Actually, ignore the previous message. Done it and it's better in the header strip:

![Screenshot 2020-06-29 at 21.57.15.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/3526fe77-1f6f-4325-a247-c37158b23dd6)

Note how I've also turned it off in the card on this page, to avoid showing it twice, which was a bit noisy

**Comment by malqinneh** [comment]
Thanks Steve!

**Comment by valgrimm** [comment]
This looks great! Kudos to you both. I'll refer to Sandra for review

**Comment by valgrimm** [comment]
While prepping the review doc, I just realized I missed a requirement. Sandra wanted to specify in a big visual way what DevRel is sponsoring specifically for each event. Is there a way to expose the "Supported by Mozilla" tag in the header on the Event Detail page as a custom text field that can say briefly what was supported? e.g. up to 20 letters followed by the word "Sponsor"?
Sorry this got to this stage before I caught that . . . :(

**Comment by stevejalim** [comment]
Rather than free text + "Sponsor", it'd be cleaner to just allow some free text in the label + a keep the control to decide whether a label is shown at all or not. We could make the default text be "Sponsored by Mozilla" if you want

Let me know if that works for you and I'll do it

**Comment by valgrimm** [comment]
Perfect! Yes. Thank you.

**Comment by valgrimm** [comment]
@sandrapersing for review

**Comment by sandrapersing** [comment]
Works for me thanks

**Comment by valgrimm** [comment]
@stevejalim  ok to deploy
