### ISSUE TITLE
Three featured events on Event page instead of two

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1605]
This is to make the featured events cards smaller; in general we will not feature three events

**Comment by stevejalim** [comment]
> This is to make the featured events cards smaller; in general we will not feature three events

I think I'm missing something here: if we allow the layout to take up to three Events in the featured section, they will currently only be rendered smaller if there are three to show, else the layout uses the two-card sizing, ie:

```
[      Event 1     ] [     Event 2    ]
```

Are you needing the featured panel in Events to be like the following?

```
[ Event 1  ]  [ Event 2  ]  [  Blank  ]
```  

If so, we could support the idea of adding a 'Spacer' element to a Featured panel, which would basically be a card with no content and no styling, to fill up the space

**Comment by stevejalim** [comment]
Plan: swap it out for a new block that handles 1...4 items, leaving whitespace rather than auto-resizing

Light gray background

"Featured events" header

If no topic available to provide content for the tag, don't have it - leave it a blank line (whitespace)
