### ISSUE TITLE
Reduce newsletter footer size on event detail pages

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1606]
AC:
- [ ] 40% reduction of image and text size and addition of one footer's worth of white space between the footer and event content, to be more in harmony with page layout

**Comment by stevejalim** [comment]
@valgrimm Could you provide an annotated screengrab of how you want it to look, please?

Also, I get the "Why" here -- and am wondering whether we make this the default size/layout for the newsletter panel on all pages _except for_ the homepage, where it's the current, larger size. What do you think?

Worst-case-ballparking this at 1pt/1 day, but could well be less.

**Comment by stevejalim** [comment]
Plan is:

Make a compact version of newsletter similar to compact call out - https://protocol.mozilla.org/patterns/organisms/call-out.html

We'll use this on all pages apart from homepage, so we need to retain the current version, too
