### ISSUE TITLE
Remove JavaScript and CSS topic areas

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1611]
**Change request**

**Submitted by**
Val G

**Change summary**
Remove specific CSS and JavaScript pages.

**RACI**
Responsible (makes final decision): @chrisdavidmills
Accountable: Val G, Steve J
Consulted: @sandrapersing  @havi @callahad @atopal
Informed: @mthermidor82 
_Note: R and A people need to provide feedback. C and I people’s feedback is optional_

**Due date for responses to this proposed change**
5pm Pacific Standard Time July 14

**What is the proposed date for the change to be made?**
Once Firefox, DevTools, and Mobile Development topics are live on production

**Why are we making this change?**
- These are addressed in the other topic areas
- Eliminating them would keep the size of the (already large) menu the same as it is now (after menu change)
- their contents are duplicated elsewhere, especially in the new DevTools section, and they would basically point to other topics

I can also discuss this with users during user testing. 

Please provide feedback in comments below.

**Comment by chrisdavidmills** [comment]
I am not sure we need this change request — we already have one about changing the topic menu, which covers this as well?

**Comment by valgrimm** [comment]
Revised due date but still haven't heard from folks, so going ahead with this one now that DevTools section is live. Only unpublishing JavaScript and CSS topic sections and removing from menus, not deleting.

**Comment by valgrimm** [comment]
done
