### ISSUE TITLE
Add MDN to Products & Technologies Menu and navigation

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1612]
### Change request

**Submitted by**
Val G

**Change summary**
Add MDN to navigation in three places:
- As card in Products & Technologies dropdown
- At  end of nav
- Under Communities section
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/a4e936a6-ecaf-4412-b138-91ba7b3dcc7e)

**RACI**
Responsible (makes final decision): @chrisdavidmills
Accountable: Val G, Steve J
Consulted: @sandrapersing  @havi @callahad @atopal
Informed @mthermidor82 
Note: R and A people need to provide feedback. C and I people’s feedback is optional

**Due date for responses to this proposed change**
5pm Pacific Standard Time July 14

**What is the proposed date for the change to be made?**
Once approval is granted, if it is.

**Why are we making this change?**
To ensure that visitors are aware of MDN and emphasize its role as part of Mozilla's support for developers. 
Previously this was included but for some reason unclear to me it was eliminated in the redesign, and I wish to reinstate it. 

Please provide feedback in comments below.

**Comment by chrisdavidmills** [comment]
Yes, I'm fine with this.

**Comment by valgrimm** [comment]
Ok, nobody else has expressed an issue with this and I pushed the original deadline, but we need to get ready for hard launch, so I'm implementing. It is a change that is easy to revert.

**Comment by stevejalim** [comment]
@valgrimm Adding this card is non-trivial because it's adding something fundamentally new to the Protocol nav layout, so will need more cross-browser testing etc.

The nav was designed to have just one card, and I think two is overload, too.

Could we swap the FF Developer promo with the MDN promo card in the Communities Dropdown instead, please?

**Comment by valgrimm** [comment]
Yes, good solution!
