### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1621]
Before we hard launch, it's definitely worthwhile doing some load testing to see how much we can push the current k8s configuration.

- [ ] Load testing discussed between @limed and @stevejalim (and any other interested parties)
- [ ] Load testing planned
- [ ] Load testing carried out
- [ ] Follow-up actions ticketed for immediate follow-up

**Comment by stevejalim** [comment]
@limed Would you Slack me to arrange a discussion about this when it suits you next week?

**Comment by stevejalim** [comment]
cc @valgrimm for awareness

**Comment by stevejalim** [comment]
https://github.com/FutureSharks/invokust could be a nice solution, as Locust.io is nicely configurable and Lambda is likely cheaper than EC2

**Comment by valgrimm** [comment]
Have contacted Kadir and Havi for load number suggestions/insights

**Comment by valgrimm** [comment]
Havi gave useful info, forwarded to Steve in email

**Comment by stevejalim** [comment]
Here's my plan

- [ ] install locust
- [ ] configure locust
  - [ ] pages
    - [ ] all structural pages we know will exist in the site
    - [ ] a topic
    - [ ] an event
    - [ ] an article
    - [ ] a video
    - [ ] a content page - the about page

  - [ ] include JS and CSS requests for each pages
  - [ ] test search with incremental, non-cacheable versions

- [ ] try it hosted locally
  - [ ] load test Staging CDN
  - [ ] load test Staging directly

- [ ] report on throughput of stage so far
- [ ] get it working on lambda if non-massive
  - [ ] load test Staging CDN
  - [ ] load test Staging directly
- [ ] report on throughput of stage so far
