### ISSUE TITLE
As a site visitor, I want to know which events are online

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1643]
AC: Add an "Online" checkbox to the location filters

**Comment by stevejalim** [comment]
Do you want "Online" to be one of the options in the (currently named) Countries section? (If so, we should rename that Locations, and perhaps we should do that _anyway_)

Or would you like "Online" to be a checkbox in a standalone section? If so, I wonder what we could call that section? We could call that section "Type" and then have "Online" and "In person" as the two options

**Comment by valgrimm** [comment]
> Do you want "Online" to be one of the options in the (currently named) Countries section? (If so, we should rename that >Locations, and perhaps we should do that anyway) ✔️ 

As above. Kudos!

**Comment by stevejalim** [comment]
Ballparking a 1pt, conservatively, as this might be as simple as adding a fake "Online" country to the options, or it might involve going down the rabbit hole

**Comment by valgrimm** [comment]
✔️
