### ISSUE TITLE
As a developer, I want to find out how to get involved with development projects at Mozilla

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1645]
Change request

Submitted by
Val G

Change summary
-Add "Get Involved" link in navigation bar before (forthcoming) search field
![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/54b8b14b-acab-4376-80e3-717a201f37ef)
-Add "Get Involved" link to "Communities" tab in nav

RACI
Responsible (makes final decision): @chrisdavidmills
Accountable: Val G, Steve J
Consulted: @sandrapersing  @havi @callahad @atopal
Informed @mthermidor82 
Note: R and A people need to provide feedback. C and I people’s feedback is optional

Due date for responses to this proposed change
5pm Pacific Standard Time July 14

What is the proposed date for the change to be made?
After approval and Get Involved page is created

Why are we making this change?
User feedback indicated 

Please provide feedback in comments below.

**Comment by stevejalim** [comment]
@valgrimm There's definitely no space to put another item in the nav. We'll gave to find another place for it, I'm afraid

**Comment by chrisdavidmills** [comment]
Could things like "About" and "Get involved" go in the footer?

**Comment by valgrimm** [comment]
Ooh, or put About in the footer and put "Get Involved" up top?

**Comment by valgrimm** [comment]
Tabling, will work into product pages
