### ISSUE TITLE
As a Tech Speaker, I want to promote my work / As Mozilla DevRel, I want event organizers to consider Tech Speakers

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1648]
Change request

Submitted by
Val G

Change summary
Change primarily based on Tech Speakers, but not only
Add the following people features:
- Add module to person page to list up to four "Posts" (video/article card links) or External Links associated with that person (based on the "What we're developing" module on the Topic pages/Event content module on the Event detail pages) but + a conditional "See more" button that appears if there are more than four items
- Create filtered Posts page view that displays the content by this person

RACI
Responsible (makes final decision): @chrisdavidmills
Accountable: Val G, Steve J
Consulted: @sandrapersing  @havi @callahad @atopal
Informed: @mthermidor82 
Note: R and A people need to provide feedback. C and I people’s feedback is optional

Due date for responses to this proposed change
5pm Pacific Standard Time July 14

What is the proposed date for the change to be made?
Likely conditional on Tech Speakers program continuing. If it isn't, this doesn't make so much sense. When Steve has time to implement and I have time to associate the content. Before hard launch would be preferable, if possible.

Why are we making this change?
To address previously-provided requests related to the people page.

Please provide feedback in comments below.

**Comment by stevejalim** [comment]
> Create filtered Posts page view that displays the content by this person

Off the top of my head this could be done either as:
* a dedicated view which shows Posts pre-filtered to a particular user, but where there is no option to explicitly select a Speaker to filter by
* a list of "Speaker" checkboxes in the filter sidebar, which is added to as Posts are associated with new Speakers (but this list could get v long over time)

Neither of these is ideal, IMO, so would be good to bounce around a bit

**Comment by valgrimm** [comment]
> a dedicated view which shows Posts pre-filtered to a particular user, but where there is no option to explicitly select a Speaker 
> to filter by
✔️ 

If they want to filter by someone else, they could go to their page.

**Comment by valgrimm** [comment]
@havi @sandrapersing ?

**Comment by valgrimm** [comment]
This is a stretch goal for hard launch, might not be realistic

**Comment by stevejalim** [comment]
@valgrimm I suggest we split this into two tickets:

1) the "my work" panel (with a customisable title) using the common four-up layout. If you can suggest a good default display name for this now, that'd be epic

2) something for handling pre-filtered links + the 'see more' link in the "my work" panel

**Comment by valgrimm** [comment]
Works for me. #1 above is the priority.
