### ISSUE TITLE
Determine work needed to move DevPortal to mozilla.dev from current domain

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1651]
Context: This is part of DevRel reorganization, Hacks would move to mozilla.dev/blog. 

This will involve redirects in some way but @stevejalim is going to discuss with Ed Lim.

Question: Does Mozilla already own mozilla.dev? Is there a stake in it elsewhere in the org? @chrisdavidmills

**Comment by chrisdavidmills** [comment]
@valgrimm looks like we've already registed it: https://www.whois.com/whois/mozilla.dev

**Comment by limed** [comment]
FWIW we already own and host mdn.dev

**Comment by stevejalim** [comment]
I've started a Google Doc to capture questions and decisions and thrash out the bits in between: https://docs.google.com/document/d/1miSEeDehVkUXDvce0M0EKaqZLdsTuztPTruyFg3fdGE/edit#

Please use that doc to add notes or ask questions, else this thread will rapidly become unworkable as a way to capture requirements
