### ISSUE TITLE
Create menu logos for Web Compatibility, Mobile Dev, and Security and Privacy

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1658]
AC
- [ ] no "d" in a box logos anymore
- [ ] SVG icon for each Web Compatibility, Mobile Dev, and Security and Privacy in same style and sizes as existing icons used for Products and Technologies

**Comment by valgrimm** [comment]
@malqinneh I welcome your thoughts on this. Are there any icons you saw, for example in the icon typeface you were considering before, which could be reused for this purpose?

**Comment by valgrimm** [comment]
Hi @malquinneh -- would it be possible to have one for Web Compatibility to start with?  The other two can wait. The key concept is being able to use the web on different OSes and devices. Rather complex, I know.

**Comment by malqinneh** [comment]
Sorry about that @valgrimm - forgot to reply to your comment last Thursday.

I can definitely get some icons for you. I'll try and do that by today/tomorrow if that's OK.

**Comment by valgrimm** [comment]
No worries! That is totally ok. I just didn't want to forget to followup and have you under time pressure. Next week is even fine. Web Compat would come first as it is already live. Thanks for your help!

**Comment by malqinneh** [comment]
Checked the symbols library and there should be icons included for:
- Web Compat
- Mobile Dev
- Security and Privacy

See attached image below:
<img width="2002" alt="image" src="https://user-images.githubusercontent.com/4819906/87162605-2894a500-c294-11ea-9daf-1c590268edfe.png">

cc @stevejalim can you check the exported icon set to make sure those are included?

**Comment by valgrimm** [comment]
Perfect! Wonderful! Kudos! :D Thank you Mustafa!

**Comment by stevejalim** [comment]
Yep they should be in https://github.com/mdn/developer-portal/tree/master/data

**Comment by stevejalim** [comment]
@valgrimm Is this still on me to implement? The changes should just be uploading the icons for the topics on their Meta tab.

**Comment by valgrimm** [comment]
Ah, so this is accessible to me? I will do.

**Comment by stevejalim** [comment]
@valgrimm should be fine, yeah - I'd check them all on dev/stage first tho in case any need some size tweaking (unlikely, but possible)

**Comment by valgrimm** [comment]
fixed
