### ISSUE TITLE
Featured events area header should read "Featured" not "Featured events"

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1671]
Came up in Sandra review of 1604.

AC:
- [ ] Featured events area header should read "Featured" not "Featured events"

**Comment by stevejalim** [comment]
Fixed and merging without code review as it's a seven-character deletion

![Screenshot 2020-07-10 at 16.10.29.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/c4c45fcf-bb73-41d6-8131-ea30044cbc11)
