### ISSUE TITLE
Make topic splash at bottom of homepage match the order in P&T nav menu

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1679]
Topics should be listed with the top to bottom ordering from the nav menu in the topic splash. So for example, Web Compat, DevTools, Firefox in the top row, with focus on where items appear in menu and not where they are in list in back end.

Does not need to be dynamic, could be manually adjusted by dev. 

![image.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/835ba41e-ce53-426c-a103-f0cee18c8b3e)

_*stretch*_ goal for hard launch

**Comment by stevejalim** [comment]
@valgrimm This is being deployed to Prod now. The only minor gotcha I noticed while checking on dev pre-release is that if there is a Topic that is hidden in the nav, it is not (currenlty) hidden in the topic block, so it would make sense to drag those down the ordering, too, if they are appearing in front of the items you want to prioritise

**Comment by stevejalim** [comment]
@valgrimm Ah ha, looking at prod now it's deployed it appears you'd already done that :star:
