### ISSUE TITLE
"Blog" link needed to Hacks

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1681]
Acceptance Criteria

- [ ] The main nav has a link to "Blog" , which links to /blog/
- [ ] /blog/ is a redirect to https://hacks.mozilla.org
- [ ] To make space for the Blog link, we move "About" to the footer of the site

**Comment by stevejalim** [comment]
cc @valgrimm To confirm AC based on Chris's latest comments in the planning doc

**Comment by valgrimm** [comment]
@chrisdavidmills look good to you? Seems fine to me.

**Comment by chrisdavidmills** [comment]
@valgrimm yup, LGTM.
