### ISSUE TITLE
Header logo and main menu

### ISSUE THREAD

**Issue by schalkneethling** [mdn/developer-portal#1709]
## Describe the bug

Some cleanup needed in the header with regards to the logo as well as the `Products & Technologies` as well as the `Communities` top-level menu entries.

## Possible solutions

- [ ] The logo has a background image set on the anchor element but, also an inline version using an image element. We can replace the inline image with something like `<span class="visually-hidden">Mozilla Developer</span>` and stick with the background image

- [ ] We also have the background logo image defined in two places as: `.header .mzp-c-navigation-logo a` and `.mzp-c-navigation-logo a`. One of these can be cleaned up.

- [ ] The top-level entries for both Products & Technologies and Communities have a class called `.mzp-c-menu-title` with a `::before` pseudo-element adding a base64 SVG version of the text already present.
    - Not sure if there is a valid reason for the above, but seems to me like we can safely remove the base64 image
- [ ] Add "hidden" accessibility nav to all pages

**Comment by schalkneethling** [comment]
## Accessibility nav

### HTML

```
<ul id="nav-access" class="nav-access">
  <li>
    <a id="skip-main" href="#content">Skip to main content</a>
  </li>
  <li>
    <a id="skip-language" href="#language">Select language</a>
  </li>
  <li>
    <a id="skip-search" href="#main-q">Skip to search</a>
  </li>
</ul>
```

### SASS

```
/*
Keyboard & screen reader skip link menu
********************************************************************** */

.nav-access {
    width: 100%;
    position: absolute;
    top: -20em;
    z-index: 1001;

    a {
        position: absolute;
        left: 0;
        right: 0;
        background-color: rgba(255, 255, 255, .9);
        padding: 12px 10px;
        font-weight: bold;
        text-align: center;

        &:hover,
        &:focus {
            box-shadow: 3px 3px 5px #aaa;
            top: 20em;
            text-decoration: none;
        }
    }
}
```

**Comment by stevejalim** [comment]
> Not sure if there is a valid reason for the above, but seems to me like we can safely remove the base64 image

If removed, we lose the close-trigger on expanded sub-menu in mobile viewport mode, so leaving it as it currently is. Hope that's cool.
