### ISSUE TITLE
Post-sweep action

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1733]
This ticket is just a placeholder

See [JIRA ticket](https://jira.mozilla.com/browse/SE-1172) for details

**Comment by stevejalim** [comment]
I have a plan for what i want to do with that JIRA-ticketed item - see update

**Comment by stevejalim** [comment]
Keeping this ticket around as a reminder to look in JIRA

**Comment by limed** [comment]
Closed out jira ticket as cancelled
