### ISSUE TITLE
Create redirect from http -> https for developer-portal

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#22]
We need to create a redirect in the django app using something like https://docs.djangoproject.com/en/2.1/ref/settings/#secure-ssl-redirect. This is due to the fact that we use gunicorn and a classic ELB both of which can't actually do the redirect

**Comment by stevejalim** [comment]
This is re-opened because the SSL redirect broke some k8s health checks. This is going to be fiddly to debug/test because it requires a deploy to confirm. 

I wonder how easy it'd be to get production parity in a local build...
