### ISSUE TITLE
Refactor internal/external resources

### ISSUE THREAD

**Issue by liamnewmarch** [mdn/developer-portal#224]
Currently on the site we have two groups of resources that an author can add – internal and external:

* **Internal resources** (_Article_, _ContentPage_, _Event_, _Person_, _Topic_, _Video_, etc) represent an actual page on the site, and can also be displayed as a card on other pages.
* **External resources** (_ExternalArticle_, _ExternalEvent_, and _ExternalVideo_) inherit from Wagtail’s _Page_ but do not exist in the URL structure – they are only ever displayed as cards.

Note that the external resources each have a corresponding internal resource. This means there are common fields, properties and methods which are duplicated  between resources (e.g. [1][1], [2][2]), tightly coupling them. In addition there is some [gnarly custom logic][3] to query multiple resource types (in code, rather than at a database level) which isn’t very scalable.

Some thoughts on solutions. The non-DRY models could probably be refactored to mixins, but I think sorting out the query logic would require introducing common parent classes. I don’t think the migrations for that would be trivial either.

[1]: https://github.com/mdn/developer-portal/blob/master/developerportal/apps/articles/models.py#L289
[2]: https://github.com/mdn/developer-portal/blob/master/developerportal/apps/externalcontent/models.py#L165
[3]: https://github.com/mdn/developer-portal/blob/master/developerportal/apps/common/utils.py#L17

**Comment by stevejalim** [comment]
Heya @liamnewmarch - couple of initial thoughts:

> sorting out the query logic would require introducing common parent classes

Could we get away with abstract parents/base classes, keeping DB schema unchanged?

> External Resources... inherit from Wagtail’s Page but do not exist in the URL structure – they are only ever displayed as cards.

Would these be better modelled as Snippets? (If they need to be Orderable, then a Snippet is definitely not the right fit)

**Comment by liamnewmarch** [comment]
Thanks @stevejalim 

> abstract parents/base classes, keeping DB schema unchanged

That sounds good, but then I think you wouldn’t be able to query the base class? Ideally I’d like to be able to do something like `ArticleBasePage.objects.filter()` and get a mix of `ArticlePage` and `ExternalArticlePage` (or whatever naming convention we decide). That feels like it might be getting into [django-polymorphic][1] territory?

> Would these be better modelled as Snippets?

Possibly! I think that might be what I’m looking for, so long as snippets are editable via the Wagtail admin?

[1]: https://django-polymorphic.readthedocs.io/en/stable/

**Comment by atopal** [comment]
We decided not to do this, because we can optimize the look up in the same way that is in the comment above.
