### ISSUE TITLE
Featured article Cards lack default image

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#225]
If you add a feature article to the homepage, but it lacks an associated image, there doesn't appear to be a fallback image, yet an image for the Article is not mandatory.

This looks like the relevant file and line:

https://github.com/mdn/developer-portal/blob/99c471b1f68e05db717ec6e750764f6c38737805/developerportal/templates/molecules/card-featured.html#L12

**Comment by stevejalim** [comment]
@liamnewmarch Happy to fix this if you can tell me which image you want used as the go-to default

**Comment by stevejalim** [comment]
![Screenshot 2019-09-25 at 15 18 57](https://user-images.githubusercontent.com/101457/65609710-23d25f00-dfa8-11e9-9c9b-c451975f9e6c.png)

**Comment by liamnewmarch** [comment]
Thanks @stevejalim I’ll chat to our designer and let you know.

**Comment by dcgauld** [comment]
Nice catch, `templates/molecules/card-featured-primary.html` will probably need updating too. I think we're good to use the same placeholder image as the internal articles @stevejalim.
