### ISSUE TITLE
Ops: make Redis available in k8s deployment

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#255]
The changes required for https://github.com/mdn/developer-portal/issues/139 including adding Redis, because Celery no longer works with a postgres backend.

As such, merging the PR for that issue is blocked (or risks breaking staging, in real terms) until redis is available and its location is exposed via a `REDIS_URL` env var.

**Comment by stevejalim** [comment]
Heya @limed - if you have time/headspace for this, that would be epic. It's not super-urgent, though as the Celery PR mentioned above can still be reviewed etc.

**Comment by limed** [comment]
@stevejalim see #261 I believe that even exposing the environment variable the app still needs a celery worker? If so let me know

**Comment by limed** [comment]
See https://github.com/mdn/infra/pull/305 where the redis cluster was created in AWS

**Comment by stevejalim** [comment]
> limed: I believe that even exposing the environment variable the app still needs a celery worker? If so let me know

@limed yeah you're right. Having redis available is only half the deal, but it at least lets Django put Celery jobs into redis and not `500` because it can't find Redis. 

The next step is, indeed, getting k8s to run a Celery worker process. It's going to probably have to come after https://github.com/mdn/developer-portal/pull/256 is merged, else the worker will die. I'll make a separate ticket for it now

**Comment by stevejalim** [comment]
That separate ticket is https://github.com/mdn/developer-portal/issues/267
