### ISSUE TITLE
Use Jinja2 as default templating language

### ISSUE THREAD

**Issue by dcgauld** [mdn/developer-portal#273]
Do we think it's worth migrating over to using Jinja2 for templating? Wagtail have a [fairly comprehensive guide](http://docs.wagtail.io/en/v2.6.2/advanced_topics/jinja2.html) on what might be required. We entertained using it at the beginning of the project, but figured we'd see whether we really needed anything more than Django templates before taking the plunge (especially given that Wagtail's admin uses Django templates).

For me, one of the biggest benefits would be Jinja2's [macros](https://jinja.palletsprojects.com/en/2.10.x/templates/#macros). The includes system is starting to get a little messy within the project, and allowing components to define their own parameters clearly would hopefully make using/reusing them a lot easier in the future.

**Comment by stevejalim** [comment]
@dcgauld We can swap to Jinja2 easily enough, but out of 10, how large a refactor do you think it is to start taking advantage of Jinja2, please?
