### ISSUE TITLE
Set up CDN for static site

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#293]
Partly to unblock #286 and partly just to try to ensure as much parity as possible with production, it would be good to get CloudFront set up for the staging bucket. Ideally, a decent CNAME would make sense. Maybe we could actualy use the hostname set up for the S3 bucket, given that CF would be proxying it anyway.

Outputs required:
* hostname/root URL of CDN to use
* root URL of S3 bucket if we use the existing hostname for the CDN's hostname instead.

**Comment by limed** [comment]
Looking at the documentation it appears that you only need `DISTRIBUTION_ID` which I have exposed in #294
