### ISSUE TITLE
Newsletter sign-up form presumes the user is in the US

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#295]
So, I signed up to Mozilla mailings via the form in the footer:

![Screenshot 2019-10-04 at 10 32 13](https://user-images.githubusercontent.com/101457/66197459-5b20ca00-e692-11e9-9263-a082882fffbb.png)

And when I came to unsubscribe from some (bit too many coming through...), I noticed my country was set to United States

![Screenshot_20191004-093221](https://user-images.githubusercontent.com/101457/66197513-725fb780-e692-11e9-9001-4f5cb1f1bdd6.png)

Is this OK? The screen to confirm my subscription **did** allow me to update country, but I missed it because it's downpage a bit.

![Screenshot 2019-10-04 at 10 34 54](https://user-images.githubusercontent.com/101457/66197638-b6eb5300-e692-11e9-9940-668f54adf0d2.png)

Should we add a country selector in the developerportal form? 

I appreciate that the above may all be "by design" and this is kind of yak-shaving.

**Comment by stevejalim** [comment]
@atopal @dcgauld What do you think about this? Happy to close if invalid

**Comment by dcgauld** [comment]
@stevejalim The original idea was just to replicate the behaviour of https://hacks.mozilla.org/. More than happy to add a country field if needed.

**Comment by stevejalim** [comment]
Thanks @dcgauld - in that case, let's stick with mirroring. Cheers.
