### ISSUE TITLE
Ensure tests are run with test-safe settings

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#314]
As more settings are defaulting to production ones and then overridden in local development, we should probably add `settings/test.py` for use in local and CI tests, to override any ones which need to be.

At the very least this should enforce `DEBUG=False` for a run of the test suite

In CI, `DJANGO_ENV=test` would be the way forward once we've added `settings/test.py`

**Comment by stevejalim** [comment]
@liamnewmarch What do you think?

**Comment by liamnewmarch** [comment]
Good call, yeah I agree that we should at least be running the tests with `DEBUG=False` in CI and ideally locally.

Do we need to add a new settings file for that? For example the tests pass locally when I run with `--settings=developerportal.settings.production`.

**Comment by stevejalim** [comment]
This had to be taken care of as part of https://github.com/mdn/developer-portal/pull/412 but I can't link multiple issues to a single PR with Zenhub

**Comment by stevejalim** [comment]
#412 is merged
