### ISSUE TITLE
Add CNAME (and/or CDN) for user-media in S3

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#318]
Once the bucket for #317 is set up, it'll probably need a decent public-friendly CNAME. 

It might well also benefit from a a CDN (eg Cloudfront), but there is a catch: invalidating it fom Wagtail won't be easy because Wagtail's multiple-frontend-cache-invalidation-code is written to invalidate pages across multiple **Sites**, and there won't be a Site that exists that matches the CNAME/hostname of this new CDN.

So, we might have to do some custom invalidation work if we do go with a CDN (see https://docs.wagtail.io/en/v2.0/reference/contrib/frontendcache.html#advanced-usage)

@limed - what do you reckon?

**Comment by stevejalim** [comment]
Heya @limed - having CNAMES on the buckets should help me with the CSP work #414

Suggestions: 
`media.devportal.stage.mozit.cloud` for stage maybe
and 
`media.developer.mozilla.com` for prod

perhaps?

Your call ultimately, but hope those suggestions help

**Comment by limed** [comment]
> Heya @limed - having CNAMES on the buckets should help me with the CSP work #414
> 
> Suggestions:
> `media.devportal.stage.mozit.cloud` for stage maybe
> and
> `media.developer.mozilla.com` for prod
> perhaps?
> 
> Your call ultimately, but hope those suggestions help

Yes we can do that, just know that cnaming a bucket requires me to rename the bucket (easier to recreate). I propose to name the media bucket as:

* `media.devportal.stage.mozit.cloud`
* `media.devportal.prod.mozit.cloud`

How about that?

**Comment by stevejalim** [comment]
>    `media.devportal.prod.mozit.cloud`
> How about that?

As long as Mozilla policy is OK with that domain (mozit.cloud) being one that users will see requests too, I guess that's fine. Your call! :smile:

**Comment by limed** [comment]
Hit a little snag, having a friendly name like `media.devportal.stage.mozit.cloud` that CNAMEs to the bucket will cause an SSL error[1]

>  Virtual host URLs are supported for non-SSL (HTTP) requests only. 

So unfortunately we will probably have to keep the `<bucketname>.s3.amazonaws.com`, that being said we can probably improve the situation by having a shorter bucket name. I propose the following:

* `devportal-media-stage.s3.amazonaws.com`
* `devportal-media-prod.s3.amazonaws.com`

This at least has a better  or easier to remember bucket name vs what we currently have which uses the following convention `developer-portal-<environment>-<account id>.s3.amazonaws.com`

[1]: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

**Comment by tobinmori** [comment]
@limed can we close this?

**Comment by limed** [comment]
> @limed can we close this?

Yes lets close this, we have settled on `devportal-media-<environment>.s3.amazonaws.com` as a the media bucket
