### ISSUE TITLE
Standardize on DNS naming

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#345]
Our current setup is as follows

- developer-portal-stage.mdn.mozit.cloud - The dynamic ELB backed page
- developer-portal-published.stage.mdn.mozit.cloud - The static published site

We should settle on a naming scheme, I believe we should use something like this

`developer-portal-<optional suffix>.<environment>.mdn.mozit.cloud`

This would yield as an example the following:

- developer-portal.stage.mdn.mozit.cloud - Dynamic ELB page
- developer-portal-published.stage.mdn.mozit.cloud - Statically generated site
- developer-portal.prod.mdn.mozit.cloud - Dynamic prod page
- developer-portal-published.prod.mdn.mozit.cloud - Static prod site

And then ultimately all we have to do is create a CNAME to point the prod site to developer-portal-published.prod.mdn.mozit.cloud

**Comment by stevejalim** [comment]
👏 Sounds great to me. Templated naming makes life easier.
