### ISSUE TITLE
Enable metrics/logging on staging (and prep for production)

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#355]
I gather it'll be New Relic we're using -- can we get this turned on (or can I have access if it already is), please?

**Comment by limed** [comment]
We spoke about this in a zoom conversation and I believe the initial thing we want to monitor for now is the celery queue which we can do in datadog.

I think monitoring the generated / published site will not really be needed initially

**Comment by stevejalim** [comment]
It might be good (post-alpha?) to have New Relic/something doing client-side error reporting from the static site, thinking about it

**Comment by limed** [comment]
Agreed if anything to make it in parity with kuma and kumascript

**Comment by stevejalim** [comment]
@limed How's this looking?

**Comment by stevejalim** [comment]
As our official wearer of the SRE hat, @limed, if you're happy with the metrics/logging available for Alpha, can you close this ticket? :heart:

**Comment by limed** [comment]
At the moment we have basic synthetics checks and we are tracking newrelic monitoring in issue #521 

I'm calling this good for now
