### ISSUE TITLE
Get ahead of heavily stuffed "directories" in S3

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#369]
At the moment, the `mozimage.models.MozImage` model uses the default `upload_to` path for the image. This works, of course, but there's an issue we might need to get ahead of, if we will ever need to browse those directories: all the files go into the same virtual directory / namespace, so listing/browsing the contents of a bucket can be overwhelming and might result in a client timeout in a worst case.

Is this something we need to think about avoiding? Will we be browsing the S3 bucket directly?

(One way to avoid it is to add a custom callable that generates a hash as a prefix for the file, then uses the first n chars of that hash as a prefix/shard and add it to the directory path.

eg: `abc/abcdef123456/foo.jpg`, `ddd/ddddef223344/bar.jpg`

(Though this change to the `upload_to` path would require moving existing files in S3, but that's not the end of the world)

**Comment by limed** [comment]
> @limed @escattone No rush, but what do you guys think of this? A problem or a non-problem? How do other projects at Mozilla organise their S3 assets?

I don't know how other projects in mozilla does this but I like the idea of using a hash as a prefix to the file.

To answer your question about whether we will be browsing the s3 bucket directly I don't think we will do it a lot unless we are trying to debug an issue, so if this takes lots of dev cycles I wouldn't worry about it. But I do like the idea :)

**Comment by stevejalim** [comment]
Thinking about this more, it would be handy to do "just in case", and would be similar to how things are done in MDN (there they use `YY/MM/DD` 'path sharding' which is an easier approach to browse through).

Doing this before we hit proper production would also make life a bit easier. Even if prod starts as a clone of the staging DB and bucket, there won't be that many files to move.

Will need a three-phase/three-releases approach: 

* Release 1: For each image field, we add a new callable/method for determining the `upload_to` path for it, _but this is not wired in to the model yet_. 
   A one-off script/management command will iterate through all images and copy the image in S3 from the current path to wherever the relevant new callable says it should be, based on the new logic. 
* Release 2: This will contain the changes that enable the custom `upload_to` logic in the relevant models (including a no-schema-change Django Migration for each). Once live, Wagtail will automatically look down the new paths for the files (which were copied over in the prev deploy) so it'll be a seamless swap-over.
* Release 3: Contains a management command that deletes the original, unmoved images from the root path of the S3 assets bucket -- and we should run this once we're happy that the previous two releases have no flaws.

@escattone @limed how does this sound? (I've done it before, so hopefully it's pretty sane! :smile:)

**Comment by limed** [comment]
>Thinking about this more, it would be handy to do "just in case", and would be similar to how things are done in MDN (there they use YY/MM/DD 'path sharding' which is an easier approach to browse through).

Yeah this is a good idea as well so this approach is 👍 to me

Overall this sounds good to me

**Comment by stevejalim** [comment]
Movign this back down in proirity - too much bikeshedding going on in my head,  not enough value
