### ISSUE TITLE
Tweak local docker-compose setup to not spin up a `common` container

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#370]
At the moment, the current use of `common` base container seems to result in spinning it up (locally, only) and that seems unnecessary. 

```
$ docker-compose ps
          Name                         Command               State           Ports
-------------------------------------------------------------------------------------------
developer-portal_app_1      gunicorn developerportal.w ...   Up      0.0.0.0:8000->8000/tcp
developer-portal_common_1   python3                          Up      8000/tcp
developer-portal_db_1       docker-entrypoint.sh postgres    Up      5432/tcp
developer-portal_redis_1    docker-entrypoint.sh redis ...   Up      6379/tcp
developer-portal_static_1   docker-entrypoint.sh npm r ...   Up
developer-portal_worker_1   celery -A developerportal. ...   Up      8000/tcp
```

**Comment by stevejalim** [comment]
@limed Would you mind sense-checking this for me, please?

**Comment by stevejalim** [comment]
If it's not a big deal to have it running, we can just close this ticket. Your call @limed

**Comment by limed** [comment]
I don't know if its possible to remove that, I have not done much research on this. If its not a big deal to leave this running I would just go ahead and close it.

**Comment by stevejalim** [comment]
No worries. I think if we move it out of `services` that might be all we need. Will take a pop at this while waiting for a build or similar -- not urgent
