### ISSUE TITLE
Alerting/monitoring needed on all k8s nodes (stage and prod)

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#371]
Good to get the monitoring plugged in soon, I think

**Comment by stevejalim** [comment]
@limed Is this already done, dude?

**Comment by limed** [comment]
I setup a basic synthetics check for the site so that should be done. Still working on the celery part

**Comment by limed** [comment]
So I started sending celery data from the cluster to datadog and we can start monitoring, although I am not sure what we are looking for here.

I think the bigger task (which we can do post alpha) is to start write instrumentation in the code to allow newrelic to start monitoring it (via APM)

**Comment by stevejalim** [comment]
As our official wearer of the SRE hat, @limed, if you're happy with the monitoring available for Alpha, can you close this ticket? :heart:

**Comment by limed** [comment]
Yeah so I think we are happy with monitoring on the k8s node end, there are more optimizations that can be done but it can be a post alpha thing.

Logs and such are being sent to papertrail and we have been happy with that
