### ISSUE TITLE
Add k8s env vars for CeleryBeat / scheduled worker

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#413]
See https://github.com/mdn/developer-portal/pull/412 for details, specifically this comment: https://github.com/mdn/developer-portal/pull/412/files#r336451713

- `CELERY_SCHEDULER_NAME`
- `CELERY_SCHEDULER_CONCURRENCY` should just be 1 I think - we don't need more
- `CELERY_SCHEDULER_CPU_REQUEST`
- `CELERY_SCHEDULER_MEMORY_REQUEST`
- `CELERY_SCHEDULER_CPU_LIMIT`
- `CELERY_SCHEDULER_MEMORY_LIMIT`

**Comment by limed** [comment]
I noted this in #279 but I'll repeat this here as well for clarity, I think these values should be set in the `Makefile`

**Comment by stevejalim** [comment]
Closing this because #422 takes care of it instead
