### ISSUE TITLE
Create production-setup data fixture

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#420]
This should bootstrap the minimum essential data + Pages (eg Homepage, Topics, Videos, Articles, People) and their dependent parents so that we can bring up an effectively empty prod site, ready for content

Also should include roles

**Comment by stevejalim** [comment]
@atopal @valgrimm - am wondering, given this is just a one-off thing, if it's easier if i just set up the skeleton pages manually next week.

**Comment by atopal** [comment]
Yeah, that's fine Steve.

**Comment by stevejalim** [comment]
Done manually on prod
