### ISSUE TITLE
Redis URL environment variables

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#430]
Looking back at our redis setup (which is similar to `kuma`) it does appear that we have the the option to add the `/1` url at the end of the redis URL. I know mentioned that in comment https://github.com/mdn/developer-portal/pull/412#discussion_r336453776 its not available, but looking back I think this is possible.

So I will go ahead and expose the following URL's in the environment variables:

* `REDIS_BASE` - Base URL in the form of `redis://<url>:6379/`
* `REDIS_URL` - Same as base URL but I think we can change this to `redis://<url>:6379/0`
* `REDIS_URL_1` - URL in the form   `redis://<url>:6379/1`
* `REDIS_URL_2` - URL in the form  `redis://<url>:6379/2`

Note that `REDIS_URL_1` will map to `CELERY_RESULT_BACKEND` in the pod

**Comment by limed** [comment]
@stevejalim based on this does anything I am saying here make sense? Will there be any code changes you need to do?

**Comment by stevejalim** [comment]
@limed Yeah - if we do this, i'll need to amend some code that deliberately stops startup if we get a REDIS_URL that features a database number"

See: 
* https://github.com/mdn/developer-portal/blob/master/developerportal/settings/base.py#L335
and
* https://github.com/mdn/developer-portal/blob/master/developerportal/apps/common/settings_helpers.py#L10

If you'd rather we go with specific, explict Redis DB references, I/we can throw repurpose this code to complain if there is **not** a DB reference in the Redis URL -- let me know.

**Comment by limed** [comment]
> @limed Yeah - if we do this, i'll need to amend some code that deliberately stops startup if we get a REDIS_URL that features a database number"
> 
> See:
> 
>     * https://github.com/mdn/developer-portal/blob/master/developerportal/settings/base.py#L335
>       and
> 
>     * https://github.com/mdn/developer-portal/blob/master/developerportal/apps/common/settings_helpers.py#L10
> 
> 
> If you'd rather we go with specific, explict Redis DB references, I/we can throw repurpose this code to complain if there is **not** a DB reference in the Redis URL -- let me know.

Hmm, if its not a trivial thing to do then lets just not do this then. The way we have it right now is working so lets not mess with it unless we need to, so with that I'll just go ahead and close out PR #431
