### ISSUE TITLE
Instrument Dev Portal for launch

### ISSUE THREAD

**Issue by atopal** [mdn/developer-portal#442]
As the PM I want to have visibility into overall page traffic and individual events we care about so we can track our success and report out to stakeholders.

**Comment by stevejalim** [comment]
(I know this is an epic, but mentioning it to help sooner)

We have a GA code allocated for staging (and which is in place currently, I believe)

Talking with @sghose in Slack, it sounds like we can just re-map this to "Production", use it there and stop using it for Staging.
