### ISSUE TITLE
Ensure there is a content plan for what the alpha release needs to show

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#464]
* Future and some past events and content are added
* Required topic are added
  * Determine which topics are correct
  * Add topics
* Some links to content from topic pages as desired
* Some content for topics as desired
* People profiles (staff and speakers)
  * Figure out which people and what content to add for them
* Start page populated
  * MDN
  * Events
  * Maybe Firefox dev edition
  * Something else [?]
  * Footer
Navigation

**Comment by valgrimm** [comment]
A content plan exists
