### ISSUE TITLE
Add night/dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mdn/developer-portal#472]
Please use https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Why:
* Against pain in eyes.
* For battery.

**Comment by stevejalim** [comment]
Hi @vitaly-zdanevich - are you suggesting this as an enhancement to developer.mozilla.org? If so, this is not the correct repo for that project. 

The correct place to report issues and suggest changes for MDN Web Docs is https://bugzilla.mozilla.org/form.mdn (which is linked to from https://developer.mozilla.org/en-US/docs/MDN/Feedback)

Cheers,
Steve
