### ISSUE TITLE
Provide credentials for Mozilla SSO

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#474]
Hi Ed

Before I can merge the work for #401, we'll need the relevant credentials/config present in stage and prod.

```
OIDC_RP_CLIENT_ID=< you have this for both envs>
OIDC_RP_CLIENT_SECRET=< you have this for both envs>
OIDC_OP_AUTHORIZATION_ENDPOINT=https://<TENANT>.auth0.com/authorize
OIDC_OP_TOKEN_ENDPOINT=https://<TENANT>.auth0.com/oauth/token
OIDC_OP_USER_ENDPOINT=https://<TENANT>.auth0.com/userinfo
OIDC_OP_DOMAIN=<TENANT>.auth0.com
OIDC_OP_JWKS_ENDPOINT=<TENANT>.auth0.com/.well-known/jwks.json
```

I've sent you the value to use for `<TENANT>` via a secure route.

**Comment by limed** [comment]
I just confirmed that these values:

```
OIDC_OP_AUTHORIZATION_ENDPOINT=https://<TENANT>.auth0.com/authorize
OIDC_OP_TOKEN_ENDPOINT=https://<TENANT>.auth0.com/oauth/token
OIDC_OP_USER_ENDPOINT=https://<TENANT>.auth0.com/userinfo
OIDC_OP_DOMAIN=<TENANT>.auth0.com
OIDC_OP_JWKS_ENDPOINT=<TENANT>.auth0.com/.well-known/jwks.json
```
Can be public, I think maybe these values can go into the django settings. Its possible that we can do something like the following (using `OIDC_OP_AUTHORIZATION_ENDPOINT` as an example)

```
OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get('OIDC_OP_AUTHORIZATION_ENDPOINT', 'https://mozilla.auth0.com/authorize')
```

In doing so we get a sane default and if we want to override using the environment variable we can as well. Thoughts on this? @stevejalim
