### ISSUE TITLE
Determine who in DevRel team/in general needs accounts at what level for alpha

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#492]
Child of: 476

**Comment by valgrimm** [comment]
Hi Kadir,

Should we just automatically create contributor profiles for all of Ali's reports? https://people.mozilla.org/p/r--0jITYlVYX0CvBJRpvqTmeA==

**Comment by atopal** [comment]
yeah, that's a good idea

**Comment by valgrimm** [comment]
Tech speakers at contributor level
All Ali’s reports at contributor level
Steve, Val, Kadir as admins

**Comment by valgrimm** [comment]
Small update just discussed with Kadir. For now solution on roles is that admin will be Steve, him, Tobin, me for now, and anyone else who needs access is a contributor. Later on we will have processes and policies and so on.

**Comment by valgrimm** [comment]
got input today from ali and chris. Will implement after at end of content ready stage
