### ISSUE TITLE
Ensure that no quantum content

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#512]

**Comment by alispivak** [comment]
Developer Edition should always be the browser version we link to.
(most) logos are here: https://mozilla.design/firefox/logos-usage/

This is the Firefox developer branding we should use for the banner:
![image](https://user-images.githubusercontent.com/10145574/67863589-6aeccc00-fae1-11e9-8091-b45a7e959bd6.png)

Link for nav bar: https://www.mozilla.org/en-US/firefox/developer/
Link for the Firefox banner: https://www.mozilla.org/en-US/firefox/developer/
Content for the Firefox Developer Edition banner (if we need text): 
The browser made for developers with the latest features, fast performance, and the development tools you need to build for the open web.

**Comment by valgrimm** [comment]
Only place I saw this was homepage. Ensured that new logo used and no reference to quantum. Ticket dealt with. That was too easy. Probably didn't need own ticket.
