### ISSUE TITLE
Monitor Developer Portal

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#521]
Converted to a separate epic ticket

----

This will be done in two ways:
1) [Speedcurve](https://speedcurve.com) will monitor performance and good practice of the static/published site
2) New Relic APM will monitor the Wagtail CMS for uptime/availability + more as appropriate

----

**Original notes from @limed**

Install the newrelic python agent so that we can start monitoring the application. In order to start monitoring the application we will need to following:

* A new relic license key (@limed)
* Install newrelic agent on Docker image (@limed)
* Generate newrelic config (@limed)
* Start newrelic agent
* Start writing code to measure code performance (@stevejalim)

More info here: https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration

**Comment by stevejalim** [comment]
@limed this sounds like an Epic - shall i mark it a such and we can cut smaller child tickets that feed it?

**Comment by limed** [comment]
Yessir lets do that

**Comment by stevejalim** [comment]
@limed thinking about this, while there's some value monitoring the perf, etc of the CMS, it's not going to help us monitor the perf of the static site -- so what do you think about using client-side libs for New Relic, too? Is that something we need to get sign-off/approval to do etc or can we just drop it in? (Am thiking about privacy policy etc -- tho at the mo, the static site's users will be anonymous)

**Comment by atopal** [comment]
Steve will break this down into user stories for back end, and we'll set up Speedcurve for frontend
