### ISSUE TITLE
Make it possible for people with profiles to upload presentations

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#545]

**Comment by valgrimm** [comment]
Related user story from Trello
"As an author I want to be able to link to my presentations on my profile page" 
On the bio page, , all the person to uplaod & show their slide decks, with a title, date, title, and comment field
Reporter: Ali"
Other notes from Trello - need an icon, start first in alpha with linking to external presentations

From feedback spreadsheet also

**Comment by stevejalim** [comment]
@valgrimm @atopal This needs acceptance criteria, please

**Comment by valgrimm** [comment]
User roles (real world, not Wagtail):

- Mozilla staff in DevRel
- Mozilla staff outside of DevRel
- External NDA volunteers including Tech Speakers
In Wagtail roles, all of the above are Editors.
When these have uploaded their presentations--approval flow can't be envisioned yet, see 905 and 907.
Conference speakers and other presenters not Mozilla staff or NDAed volunteers would have to submit their presentation materials to Sandra/Val/Lucie/Leah. Val would put these on the site. 

Ideally depends on 635 given likely widespread non-portal-team access.

**Comment by valgrimm** [comment]
So part of the functionality is presentation specific, and part is generally related to files. I'm trying to put separate if related requirements in separate tickets.

**Comment by valgrimm** [comment]
An optional additional acceptance criterion is to allow visitors to view presentations embedded on presentation pages on the portal site as they can now view video, but as that is non-trivial unless there is some library just for that, so I didn't put that in the main description of acceptance criteria.

**Comment by valgrimm** [comment]
Closed, instead see 377
