### ISSUE TITLE
Topics copy for panels on homepage

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#560]
Grammar check on existing topics copy, icons are ok
Copies over from staging

**Comment by valgrimm** [comment]
Other than a comma splice in the CSS description, there are no obtrusive grammatical errors in this copy. 
However, these descriptions do not have a consistent structure and tone, and they are overly wordy. I would desperately like to clean them up. 

Not sure this is in scope. 
Need call from Kadir if I do this or defer.

**Comment by atopal** [comment]
We can take it in as a lower priority. I don't it blocks the launch though

**Comment by valgrimm** [comment]
Cleaned up this copy Friday November 15
