### ISSUE TITLE
Reduce size of topic block next to event text

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#564]
Need clarification and prioritzation from Ali
Here is screenshot
![topicblocknextoeventtext.JPG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/05220bd2-b173-4065-8dfd-c6d43772f584)

**Comment by atopal** [comment]
I think we can completely drop it.

**Comment by atopal** [comment]
The line length goes to full width when that box isn't there. We need input from design to make this change

**Comment by stevejalim** [comment]
> The line length goes to full width when that box isn't there. We need input from design to make this change

Related: a narrower box for the Topic would break the visual lines of the page grid, so seems to me to be something to approach with a design eye
