### ISSUE TITLE
Remove Latest Authors from people page

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#567]
![rmlatestauthors.JPG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/88dda333-40d2-4464-aee8-caf8788d5ad3)

**Comment by valgrimm** [comment]
From Feedback Excel

**Comment by stevejalim** [comment]
@atopal @valgrimm Is this for alpha, please? Am assuming it is
