### ISSUE TITLE
Topic pages review - Owners, Havi, final ok Kadir

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#574]

**Comment by valgrimm** [comment]
Status report:
Accounts created for all topic stakeholders and a few extras they designated

Responded and actively editing:
Browser extensions

Responded that they want accounts:
Mixed Reality

Responded with a change/changes that I have made and let them know:
WASM
Javascript

Okayed
AV1
Voice

Not responded after second meeting
Firefox Mobile

Not responded at all
WebThings
Rust
CSS

**Comment by valgrimm** [comment]
Need a call whether we go ahead with a launch displaying all topic pages given the current state of responses, which remain as in my prior comment.

**Comment by stevejalim** [comment]
@valgrimm assuming the three of us don't overlap today and @atopal and I have to wing it, what is your personal preference re the above? Keep or hide?

**Comment by valgrimm** [comment]
I think Kadir and Havi are better placed to decide than Ias they have been here longer. Sent him an email and cced Havi.

**Comment by atopal** [comment]
Yes, we launch all the topic pages. Everyone had ample time to at least have a look, all of it is content that has been shared before. I think the risk is fairly low. If anyone has an issue we can unpublish quickly.

**Comment by valgrimm** [comment]
Thank you for this decision. I feel good about it. 
How should we change the status of this ticket?

**Comment by valgrimm** [comment]
Have updated this ticket as decision has been made.

**Comment by valgrimm** [comment]
No more feedback at present time, so far some owners are keeping me updated on what to add or are maintaining themselves with my help/publishing. 
Stakeholder demo complete on Dec 9.
