### ISSUE TITLE
Add link to Mozilla mission to footer

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#577]
From Feedback excel

**Comment by valgrimm** [comment]
From Havi

**Comment by stevejalim** [comment]
@atopal @valgrimm Is this for alpha, please?

**Comment by valgrimm** [comment]
Old from feedback Excel, non-critical, therefore not alpha release

**Comment by stevejalim** [comment]
This is a code change - can you let me know the link and assign this ticket to me, please?

**Comment by valgrimm** [comment]
This is the link: https://www.mozilla.org/en-US/mission/

**Comment by stevejalim** [comment]
Note to self: Locale-independent version is https://www.mozilla.org/mission/
