### ISSUE TITLE
Add button leading to getting event sponsored to events page

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#599]
Not for alpha 
See also tickets 598, 549

**Comment by valgrimm** [comment]
The circled link (to be named "Getting your event sponsored" or something like this in future) should also be accessible via a button from the Events page, preferably in one of the sections of the page referred to with a blue arrow. 

![addbutton.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/7c312509-6477-4004-be42-b67cbc70bc1d)

**Comment by valgrimm** [comment]
Related to 598 which is about renaming the link text in the Communities menu

**Comment by stevejalim** [comment]
Now a duplicate @valgrimm ?

**Comment by valgrimm** [comment]
That was a reminder for me to make this change once the code change is live on production.

**Comment by stevejalim** [comment]
This is done. Closing
