### ISSUE TITLE
Enter all past events (after alpha)

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#630]
From 2015-2019 ViewSource
From 2017 DevRoadShow Asia
From 2019 DevRoadshow Europe and Asia

**Comment by valgrimm** [comment]
added all events in list currently but there are more, so requesting the more

**Comment by valgrimm** [comment]
Waiting on Sandra/Lucie/Leah

**Comment by stevejalim** [comment]
@valgrimm If this can hold on until after we deploy the server-paginated solution (next week once everyone is back), that would be great, just to keep the total size of `Events` from growing further just now

**Comment by valgrimm** [comment]
I already added all the stuff I already have, so waiting is fine.

**Comment by valgrimm** [comment]
Sandra asked for clarification on what info I needed and I provided. Once pagination is implemented and I have access to that info from her, this ticket can move forward.

**Comment by valgrimm** [comment]
Entered all given. If more are requested, will add them. Closing this.
