### ISSUE TITLE
Add all social media accounts including YouTube to footer

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#633]
AC 

Footer contains links to 
- [ ] https://hacks.mozilla.org/
- [ ] https://twitter.com/mozhacks
- [ ] https://www.youtube.com/user/mozhacks
- [ ] https://www.youtube.com/MozillaDeveloper

in a way that is in-keeping wiht Mozilla's [Protocol design system](https://protocol.mozilla.org/)

**Comment by stevejalim** [comment]
If it's not for alpha, can we mark this P2?

**Comment by valgrimm** [comment]
Have removed the label. Will see what priority Kadir puts on this in next sprint.

**Comment by stevejalim** [comment]
This is a code change - ping me the details and I'll sort it out

**Comment by valgrimm** [comment]
This will need to be validated by @havi 
What I have 
https://hacks.mozilla.org/
https://twitter.com/mozhacks
https://www.youtube.com/user/mozhacks
https://www.youtube.com/MozillaDeveloper

@atopal I presume MDN social media is not in scope.

**Comment by valgrimm** [comment]
Hi Steve, can you set this up on staging with content mentioned in previous message and I can send to Havi for approval?

**Comment by stevejalim** [comment]
Sure thing. Just text links? Or icons too?

Also, any preference for where in the footer they go? (Is there a different Mozilla site we can use as a reference?)

**Comment by valgrimm** [comment]
Hi Steve, I made a mockup. The result doesn't have to be exactly like this, but this should give an idea. Will email you the xcf so you can grab icons from there.
Then to put on staging and check with Havi. This setup is inspired by that on the Hacks blog. 

![footer-preview](https://user-images.githubusercontent.com/56933147/70724896-bd81f080-1cfb-11ea-8da4-23e25c5ce00c.png)

**Comment by stevejalim** [comment]
Here are some WIP screenshots @atopal @valgrimm 

**Desktop**
<img width="1141" alt="Screenshot 2019-12-20 at 18 08 48" src="https://user-images.githubusercontent.com/101457/71280698-dcaffc00-2353-11ea-9af9-89536e638052.png">

**Medium viewport**
<img width="748" alt="Screenshot 2019-12-20 at 18 09 39" src="https://user-images.githubusercontent.com/101457/71280730-fb15f780-2353-11ea-9e58-1957194f4fd1.png">


**Mobile viewport**
<img width="386" alt="Screenshot 2019-12-20 at 18 09 50" src="https://user-images.githubusercontent.com/101457/71280731-fb15f780-2353-11ea-809d-727f78ed2dc4.png">


I need to cross-browser test, but checking in with this now in case a change of direction is needed.

**Comment by atopal** [comment]
Looks good to me Steve

**Comment by stevejalim** [comment]
Deployed to production
