### ISSUE TITLE
We need an instrumentation spec

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#647]
There's an epic to have instrumentation, but no clarity yet on what that should be and which areas in particuar we want to monintor

We'll have Google Analytics plugged in, but no custom event triggering (yet).

We'll also (post-alpha, it's looking like) have additional metrics from New Relic, but this are TBD

**Comment by stevejalim** [comment]
@kadir - we have Speedcurve enabled, but nothing specific configured. Do you have time to add some detail there, please?

**Comment by atopal** [comment]
I've set up page load for some basic pages, which should be fine for the start. We can set up meaningful performance KPIs later.

**Comment by atopal** [comment]
Instrumentation Spec: https://docs.google.com/document/d/1JZZDj9gxvAliVjvZCXffRyQIpaviBnHEQi1CQoi7EVs/edit#

**Comment by atopal** [comment]
No additional requests were made, so we're good to go for now.
