### ISSUE TITLE
The javascript filters for list views can get in a muddle

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#651]
After playing around with a few checkbox filters, it's not uncommon that the state of the results shown stops robustly reflecting what's been selected.

This needs a little exploration, I think

**Comment by atopal** [comment]
Steve will invest half an hour trying to replicate, and we'll triage again then

**Comment by stevejalim** [comment]
Got it (well, at least part of it): if you load a page with a pre-configured querystring (eg `?topics=rust`) - which may be because someone's made a pre-filtered link or you're simply back-arrowing from a previous page, the checkbox in the filters panel is ticked. 

HOWEVER, if you untick it, the querystring is **not** updated and the filtering doesn't change.
THEN if you retick the different filter, that one is added _again_: `?topics=rust,rust`
THEN if you tick a different filter, that one is added, too: `?topics=rust,rust,html`

So, the behaviour when un-ticking a pre-selected-via-querystring option box is worth checking over.

**Comment by stevejalim** [comment]
@atopal Am calling this a p1 and will get on to it ASAP

**Comment by stevejalim** [comment]
Also see #730 for a thing that can be fixed at the same time as this
