### ISSUE TITLE
"Communities" parent page needs content

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#665]
https://developer-portal-stage.mdn.mozit.cloud/communities/ is a parent page of a couple of things, but currently has no content of its own. 

We will need to have _something_ on this page because we need it to appear in the menu (and it's not possible to do the 'only have a draft' trick that we do with Videos, because we don't need "Videos" in the nav, but we do want "Communities" in the nav, so we need the page to be published/live.

Do we already know what we want to put on /communities/ @valgrimm, please?

**Comment by valgrimm** [comment]
Hi Steve, We don't know, but I can come up with a temporary solution and run it by Kadir. Warm regards, Val
