### ISSUE TITLE
Confirm "external promo" content on homepage

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#667]
Does thi permanently want to remain as on staging? (minus reference to quantum of course)

![promocontent-staging.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/647c2164-386d-45dc-91a1-5504b73434d3)

**Comment by stevejalim** [comment]
I wouldn't worry about any content on Insurance - once we're properly in production, we'll regularly copy content from Prod to Stage, overwriting Stage each time. (Details/workflow TBC, though)
