### ISSUE TITLE
Enable object level versioning on published site

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#674]
Enable `S3` object versioning for published s3 bucket

**Comment by limed** [comment]
I have concerns that if we enable this it might drive cost up since we do get charged for every version of every object. And seeing that wagtail for now bakes the entire site and re-upload them the cost and number of objects can increase exponentially.

This requires more discussion on whether we want to go down this route

**Comment by stevejalim** [comment]
Let's not do this - it was to give us an extra layer of redundancy, but the risk of mushrooming storage is real
