### ISSUE TITLE
Get Voice topic icon, get text approved

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#687]
Will need to get ok of description for Voice and get an icon (currently placeholder) from Jofish Kaye and David Bryant. Have placeholder icon and Val wrote the text.

**Comment by valgrimm** [comment]
Updated text based on their input, but they haven't sent an icon. Have proposed just a letter V as th temp icon.

**Comment by atopal** [comment]
Steve has updated the place holder with a neutral icon, which we can use until we get a better placeholder.

**Comment by valgrimm** [comment]
As this won't be resolved before release, how should we modify this ticket?

**Comment by atopal** [comment]
Let's close this one and and have a low priority ticket for just the icon.

**Comment by valgrimm** [comment]
Merged to #807, I think
