### ISSUE TITLE
Add custom code to monitor performance in New Relic

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#710]
This is the final step in the Monitor Developer Portal epic.

Note that that most of what can be monitored is Wagtail, over which we have little practical control (though we can submit optimisations to the project of course :heart:). So, custom monitoring here may not be all that enlightening.

However, it does make sense to put effort into monitoring key areas where we have custom code. The most relevant one is the static build pipeline, because it would be _really very useful_ to be able to get alerts if the overall build time grows (given we're regenerating the entire static site at the moment) 

AC:
- [x] New Relic shows a record of how long every static build takes

**Comment by limed** [comment]
Epic for this is #713

**Comment by stevejalim** [comment]
Hmm 

> Custom events sent with the agent APIs are not compatible with high security mode.

says the NR documentation

**Comment by stevejalim** [comment]
Looks like we get this "for free" with the existing NR integration and no extra code required:

The view `wagtail.core.views.serve` is what does all of the rendering when triggered by `wagtail-bakery` so the total time spent in there _by the worker_ is what we care about most. The time taken by the code which calls it is comparatively trivial, as can be seen here:

https://rpm.newrelic.com/accounts/1807330/applications/209986510/transactions (@atopal let me or @limed know if you need access to see this project)

As such, we can see that builds take an average of 35.2 seconds right now.

We can also set up alerts if that time exceeds a certain threshold, but that has to be done by an admin-level user (eg @limed) - setting that to 60 seconds for nowwould be interesting.

Next actions:
- [ ] @atopal would you agree that the metrics linked to above are enough to satisfy the AC for this ticket?
- [ ]  @limed could you add that 60-sec-limt alerting, please?

**Comment by atopal** [comment]
Yeah, works for me 👍
