### ISSUE TITLE
Image naming standard proposal ok?

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#712]
Not urgent. propose naming standard for images.

Added text to admin guide along with size guidelines from code and the info about the svg issue. See images section in admin guide.

Relevant text to this as follows:
Image naming standards
This is a proposal from Val Grimm. Not confirmed as of this writing. Images added before 12:50pm UK time on November 6 2019 do not conform to this standard. They will need to be corrected.

Name format: sitearea-yearmonthname-areaspecifictag-areaspecificinfo
Example: event-2019nov-heavy-tellerand

**Comment by stevejalim** [comment]
Hi Val

Not sure of you're talking about the display name for an image (eh what
might be used for `alt` text) or the actual filename of the image. If the
latter, I should point out that there's a 95-character limit on actual
image filenames, so your pattern might exceed that in some cases. Also, it
might be we start using obfuscated filenames/hashes/automaic unique IDs for
the actual files)

Regardless, I would suggest we lean on Wagtail's Collections to group/tag
images to make them easier to filter down when choosing a new image to
upload.

**Comment by valgrimm** [comment]
Hi Steve,
This is exactly type of answer I need.
I meant actual filename of the image. I am coming from the Stone Age just a bit in regard to that. 
Will read Wagtail collections doc. I did a tiny bit of reading about Wagtail before jumping into this, as not much time, so have basically been depending on the bits of other CMSes I have learned and the manual chapter on streamfield.

**Comment by valgrimm** [comment]
ok, noting https://docs.wagtail.io/en/v2.6.3/editor_manual/documents_images_snippets/collections.html
