### ISSUE TITLE
Add sitemap support

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#746]
We don't currently export one to the static site.

AC
- [x] Code in production
- [x] Search console show no errors for sitemap
- [x] Search console reports all pages as indexed (should be about 171)

**Comment by atopal** [comment]
Not a launch blocker, but yes, since we'll care about traffic after launch.

**Comment by stevejalim** [comment]
Reassigning to @atopal for Search console AC items

Sitemap is live on https://developer.mozilla.com - view source to see the link or go straight to https://developer.mozilla.com/sitemap.xml (which shows 179 `<loc>` nodes - ie 179 pages)

**Comment by atopal** [comment]
We need to add this to our DNS txt record to get the site in search console: 

google-site-verification=P5C3wuIoNNB44J2nG3U9iA8FAovwbKvoS9VWgpdECJU

Here are the full details: https://support.google.com/webmasters/answer/9008080#domain_name_verification

**Comment by stevejalim** [comment]
@limed can you take care of the DNS update, please? (See comment above)

**Comment by limed** [comment]
> google-site-verification=P5C3wuIoNNB44J2nG3U9iA8FAovwbKvoS9VWgpdECJU

I'm assuming you want this TXT record for `developer.mozilla.com`? I can't create it for `developer.mozilla.com` but I went ahead and created it for `_developer.mozilla.com`

**Comment by stevejalim** [comment]
@atopal Could you try now and see if Search Console picks it up?

**Comment by atopal** [comment]
I can see the entry for _developer.mozilla.com but that's not accepted by Google Search Console. It has to be developer.mozilla.com

**Comment by stevejalim** [comment]
Ah that's going to be tricky, then -- @limed said there's already one in
place for developer.mozilla.com, I think -- can that be overwritten?

**Comment by limed** [comment]
> Ah that's going to be tricky, then -- @limed said there's already one in place for developer.mozilla.com, I think -- can that be overwritten?

I think Google allows verification using CNAME's as well can we go that route?

**Comment by limed** [comment]
> > Ah that's going to be tricky, then -- @limed said there's already one in place for developer.mozilla.com, I think -- can that be overwritten?
> 
> I think Google allows verification using CNAME's as well can we go that route?

Actually thinking about it more no this route is not possible too, we can't create a TXT because we have a CNAME at that level.

**Comment by stevejalim** [comment]
@atopal OK, so the analytics.js code (and DNT support) are live now. They're kinda hard to test, because i can't seem to get analytics to load at all in FF (no console errors, am assuming it's DNT working) but I can see analytics.js loading fine in Safari.

Could you please:
* confirm that things look like they're working
* let me know if that unblocks you setting up Search Console, etc

Cheers
Steve

**Comment by atopal** [comment]
okay, I can see the portal in search console now. Only 88 pages were indexed by Google. I added the sitemap and it discovered 224 pages. No errors. 

Wagtail says that we have 312 pages, but I'm not sure how to see how many of those are actually published pages meant to be indexed.

**Comment by stevejalim** [comment]
Currently the Wagtail admin reports 311 pages. There are 82 published items of External Content, which don't appear in the sitemap

`311 - 82 == 229` 

That seems to more or less line up. 

@atopal if you can export a list of pages from GA that I can compare with the sitemap, that'd work. 

Or if you're still happy to close this, feel free

**Comment by atopal** [comment]
Yeah, I think we are okay.
