### ISSUE TITLE
Standardise SVG width for topic icons

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#781]
Slightly different-width icons mean that the content in the Topics panels on the homepage flow slightly differently.

Might be worth me downloading them, resizing them to have a consistent width and re-uploading them.

At the same time, I can do a Voice SVG if someone points me at a source icon

Example screenshot:

![maccat_firefox_62.0.jpg](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/5bc3c89e-3909-4a1e-a15b-0831a225dadf)

**Comment by stevejalim** [comment]
So, tinkering with CSS I can improve it to a certain point, but this looks like it's something that's best addressed by ensuring all the SVG icons are the same width and centred vertically and horizontally in their own files/definitions, because setting the CSS to fix the width of the icon panels and centre-aligning them does help, but also highlights how offset the "top" of some icons are.

eg: 

![Screenshot 2019-11-16 at 13.22.19.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/d2ea84a1-5df1-41a6-ae3a-be1b8fd9a7ab)


What do you think of the above @atopal - "good enough"? I am happy to try the additional step of re-cutting the SVG icons on Monday, no worries.

**Comment by atopal** [comment]
Yes, absolutely good enough, Steve :)
