### ISSUE TITLE
FF logo in nav: scale is broken in IE11

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#782]
This is zoomed in, but it's clear that IE11 isn't liking the clash between a size in the file and a _different_ size in the CSS:

![Screenshot 2019-11-15 at 11.35.12.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/926b4b2d-18d0-4697-91c8-9be16e51f4d3)

**Comment by atopal** [comment]
cosmetic defect on IE11, we're fine with that.
