### ISSUE TITLE
Go-live steps

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#787]
At **0930 PST / 1730 GMT / 1830 CET on Tues 19 November** but _not before_:

- [x] Set up CNAME for existing production CDN to _also_ serve `developer.mozilla.com`
- [x] update the hostname of the default Site (in admin settings panel) to be `developer.mozilla.com`
- [x] Merge and release PR #808  that updates the production CDN hostname as one that we are allowed to export to
- [x] Re-publish entire production site (to update 'baked in' URLs in opengraph tags) - we can do this by publishing any page in the site without making edits
- [x] send message on #devportal_team, #developer-relations

**Comment by stevejalim** [comment]
cc @limed @atopal @valgrimm - anyone got anything to add to this checklist?

**Comment by limed** [comment]
I have a question with this

> Set up new CDN on developer.mozilla.com

So currently the CDN is actually configured to respond to `developer.mozilla.com` do we really need to setup a new CDN here? Do you really mean just create a `CNAME` for `developer.mozilla.com` to point to the CDN?

**Comment by stevejalim** [comment]
@limed CNAME approach works for me - means we then don't have to update the Distribution ID

**Comment by stevejalim** [comment]
@limed @atopal while working on the sitemap ticket, I remembered (phew!) an additional step we need to do:
> - [ ] Merge and release PR that updates the production CDN hostname as one that we are allowed to export to

Will make that PR now

**Comment by stevejalim** [comment]
All done!
