### ISSUE TITLE
Add all eligible tech speakers to dev portal

### ISSUE THREAD

**Issue by atopal** [mdn/developer-portal#793]
place holder to add all eligible tech speakers to the dev portal

SUBITEMS
Add speakers from current list
Sort NDA and SSO issues for speakers on current list
Sort out gender balance issue
Plan future additions of tech speakers with Jen
How do speakers get topic tags?

**Comment by valgrimm** [comment]
AC:
All tech speakers added and regular schedule for updates

**Comment by valgrimm** [comment]
Waiting Jess return on January 13.
