### ISSUE TITLE
New Relic - relax exception cleaning?

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#797]
Heya @limed - looking at a couple of the things that NR has caught in prod celery, I'm seeing `Message removed by New Relic 'strip_exception_messages' setting` which means we don't get the full detail of the traceback.

Given that the content is all public, can you think of a reason why (eg API keys?) we need this enabled for NR? If not, maybe disabling it will give us better tracebacks

**Comment by limed** [comment]
I believe the reason why we are getting this is because we configure `newrelic.ini` to be in "high security mode", see: https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/high-security-mode#version2description

This is the comment in `newrelic.ini` for `high_security`

```
# High Security Mode enforces certain security settings, and prevents
# them from being overridden, so that no sensitive data is sent to New
# Relic. Enabling High Security Mode means that request parameters are
# not collected and SQL can not be sent to New Relic in its raw form.
# To activate High Security Mode, it must be set to 'true' in this
# local .ini configuration file AND be set to 'true' in the
# server-side configuration in the New Relic user interface. For
# details, see
# https://docs.newrelic.com/docs/subscriptions/high-security
```

**Comment by stevejalim** [comment]
Am I right that we can't turn this off without asking NR support to do it, @limed ? I think that's what the outcome of or Slack chat was

**Comment by stevejalim** [comment]
Am closing this - for now the behaviour mirrors MDN, and if we get a bug we still have the k8s logs which we can live-tail and (hopefully) live-repro the issue
