### ISSUE TITLE
Send stacktraces to sentry

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#803]
We need to start sending out stacktraces or any errors to [sentry](https://sentry.io/)

Things to do:
- [x] Create new sentry project
- [x] Create new sentry key
- [ ] Expose `SENTRY_DSN` env var
- [ ] Update developer-portal code to start capturing errors

The first 2 tasks help from cloudops and the third tasks will require work from @stevejalim

**Comment by stevejalim** [comment]
@limed I think we might need an additional step where the SENTRY_DSN is slotted into env vars, yeah?

**Comment by stevejalim** [comment]
Blocked until I know about the `SENTRY_DSN` env var being needed and available
