### ISSUE TITLE
Get Voice topic icon

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#807]

**Comment by valgrimm** [comment]
From 574

**Comment by valgrimm** [comment]
Resolves #687

**Comment by valgrimm** [comment]
Emailed David and Abraham again cced Kadir

**Comment by valgrimm** [comment]
Have icon, Steve will add tomorrow

**Comment by valgrimm** [comment]
![voice-black.svg](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/aed0cff0-7265-4569-a777-a470ee532fee)

**Comment by stevejalim** [comment]
Icon resized to 40x40 and - after battling duplicate ID torment (not Abe's fault - a side effect of using Sketch to resize the icon) - icon is live
