### ISSUE TITLE
XML doctype in the HTML caused HTML validation failure

### ISSUE THREAD

**Issue by jasoncartwright** [mdn/developer-portal#822]
Validating the HTML of https://developer.mozilla.com one of the errors is that the HTML contains an XML doctype, apparently at the top of an embedded SVG

> <?xml version="1.0" encoding="UTF-8"?>

https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeveloper.mozilla.com%2F

<img width="1196" alt="Screenshot 2019-11-22 at 15 42 38" src="https://user-images.githubusercontent.com/763913/69439382-bbe98c00-0d3e-11ea-8d1f-942b5735d5cc.png">

**Comment by stevejalim** [comment]
@jasoncartwright I'll fix that by re-uploading a better file. The original SVG came out of Sketch and I pruned out some noise, but clearly not enough

**Comment by stevejalim** [comment]
Uploaded a fixed version of the SVG to prod @jasoncartwright - waiting for the CDN to catch up then I'll revalidate and close this ticket

**Comment by stevejalim** [comment]
Confirmed - changing the SVG has made this go away

**Comment by stevejalim** [comment]
Thanks for reporting @jasoncartwright !
