### ISSUE TITLE
Determine why focal area functionality doesn´t seem to have an effect and fix if possible

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#830]
When focal areas are designated for images, this does not seem to have an effort on how they are displayed, especially relevant for oversize images. Had to trim down CSS video thumbnail to make it appear properly on CSS page in examples below.

![1d0c3158-dbdf-48d5-a220-a0e888b05dd1.png](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/11bb1aaa-3d45-4703-b1db-3756da6cd6c8)
![focalarea1.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/8a73c76b-e263-49c5-984f-38ca1de77e91)
![focalarea2.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/58c997c5-d276-4433-9b15-37e236d419c8)

**Comment by stevejalim** [comment]
@valgrimm I think part of this can be explained by the Focal Area being something that Wagtail uses when being asked to put a square peg in a round hole: the focal area is intended to help Wagtail know how to crop a rectangular image into a square one, or into a thin sliver.

The CSS of the site, however, isn't aware at all about focal areas - so if part of the pain you've had is with the slash/asymmetric design we have in some of the site (so it overlaps with bits you didn't want it to), that's something we can only manage via manual curation of images.

Does that cover your pain point, or are there more examples we can look at?

Cheers
Steve
