### ISSUE TITLE
Tabbed panels in mobile viewport mode need some attention

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#833]
![Screenshot 2019-11-25 at 14 10 30](https://user-images.githubusercontent.com/101457/69547385-67881b80-0f8d-11ea-9a14-ef86109ff615.png)

- The open/close trigger should not be overflowed with text - the text will have to be truncated (and ideally edited to avoid the need for auto truncaton)
- As with the topic filters, the `+` icon could do with a little more space below it (1~2px)

**Comment by stevejalim** [comment]
@valgrimm in the short term, can we edit "Web XR specification" to "Web XR spec"?

**Comment by valgrimm** [comment]
I don´t think folks will mind. Have fixed this on relevant page. Feel free to close if need be @stevejalim
