### ISSUE TITLE
Determine which forms solution should be used

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#836]
Tech Speaker application form in Google Forms and Sponsorship Request in Airtable
Determine if one solution should be found instead of this patchwork approach, and if so which solution

**Comment by stevejalim** [comment]
Note that Wagtail supports forms too: https://docs.wagtail.io/en/v2.7/reference/contrib/forms/index.html

**Comment by valgrimm** [comment]
This is relevant, shall investigate later, thank you!
