### ISSUE TITLE
Ensure ExternalContent subclasses are made as child pages of the relevant parent page

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#865]
While dealing with #864 I noticed that none of the subclasses of `ExternalContent` has `parent_page_types` set. This explains (I think, and would need to be 100% sure) why they are made as children of the _unreachable_ Root page, and return `None` for `page.get_site()`.

While this can be worked around, it's better to clean things up:

- [ ] Ensure each `ExternalArticle` has `Articles` in its `parent_page_types`  
- [ ] Ensure each `ExternalEvent` has `Events` in its `parent_page_types`  
- [ ] Ensure each `ExternalVideo` has `Videos` in its `parent_page_types` 
- [ ] Add a data migration to non-destructively bring this into line for existing pages
- [ ] Update documentation around the need to use the default site, added in #864

**BEFORE TACKLING THIS, ENSURE #868 IS UNDERSTOOD PROPERLY**

**Comment by stevejalim** [comment]
@liamnewmarch @dcgauld No worries if you can't answer, but does the above issue/suggestion/approach make sense to you, or is there a reason `parent_page_types` wasn't set that I am not appreciating? Cheers!

**Comment by liamnewmarch** [comment]
I’m not sure I fully understand, but in not setting `parent_page_types` this should allow all pages to be parent [by default][1]. Being more explicit here does sound like it would prevent ExternalContent from being created where it shouldn’t, so the theory sounds good to me.

[1]: https://github.com/wagtail/wagtail/blob/96965d/wagtail/core/models.py#L919-L922
