### ISSUE TITLE
Provide way to append comments to "Submit for Moderation" requests

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#872]
For example: "Release on December 10th at 10am PST" or "I added a subject tag to my profile"

**Comment by stevejalim** [comment]
That sounds like a nice feature to add to Wagtail itself. 

If we can allocate the time, I'd be happy to explore adding that as a contribution back to Wagtail

**Comment by valgrimm** [comment]
@steve: I upvote. Tell Matt it was me (:

**Comment by atopal** [comment]
Steve will see if this can be added to wagtail

**Comment by stevejalim** [comment]
We can write up and submit an RFC at https://github.com/wagtail/rfcs

**Comment by valgrimm** [comment]
Super. I shall write something up and send it to you for input and we can meet. Will do during next sprint if ok by Kadir. have assigned to me so I write first draft of req.

**Comment by atopal** [comment]
yeah, works for me!

**Comment by valgrimm** [comment]
I have created an initial draft of the RFC minus technical detail. Now I am adding it to this ticket and assigning the ticket to Steve so that where there is time he can review what I have written add this detail.
wagtail-rfcs/000-append-comments-for-moderation.md

I read the instructions for writing Wagtail RFCs before writing this RFC (https://github.com/wagtail/rfcs).
