### ISSUE TITLE
Country field for roadshow events

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#885]
When we have roadshow events that span several countries but are gathered together in one record, it isn't possible to enter anything in the country field and the result is a visible blank field on the events page with the location pin next to it. What sort of workaround could we find for this edge case?

**Comment by stevejalim** [comment]
@valgrimm We can tweak the template to not render a location if none is selected -- would that help?

**Comment by valgrimm** [comment]
Yup!
