### ISSUE TITLE
Link validation error, specific link

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#896]
![wonttakeyoutubelink-specific2.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/30a2fd4b-be81-452b-9d67-1058e0866b99)
![wonttakeyoutubelink-specific.PNG](https://images.zenhubusercontent.com/5db08cf412d6350001ab877a/fd18e8af-2a77-4ff5-82b9-13c6866d098c)

**Comment by stevejalim** [comment]
@valgrimm What happens if you embed the non-shortened URL? ie the one in the acutal URL bar of Firefox?

**Comment by valgrimm** [comment]
Ah yes should have said. Neither form of the URL works.

**Comment by stevejalim** [comment]
@valgrimm When i go to https://youtu.be/1CcuurW-cG4 I'm told `This video is private`

![Screenshot 2019-11-28 at 15 44 04](https://user-images.githubusercontent.com/101457/69819069-0911a600-11f6-11ea-9623-49521510a23c.png)

**Comment by valgrimm** [comment]
yes, but so are othe other videos . . . or at least the others are unlisted. hm. I'll see if I can change the video settings.

**Comment by valgrimm** [comment]
It is set to private and has a problem, makes sense now.
