### ISSUE TITLE
Better pagination solution for static site

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#901]
Now that the site is filling up with content, the "load it all and hide most of it" approach needs review.

* The Posts page is the biggest issue: currently 9.99 MB / 17.52 MB uncompressed 
* The People page is currently 2.58 MB / 2.38 MB uncompressed

**Comment by atopal** [comment]
We'll be looking into how hard it is to move to dynamic site, where we'd get this for free.
