### ISSUE TITLE
Set up back-syncing of Production state (DB and S3 user-media assets) from prod to staging.

### ISSUE THREAD

**Issue by atopal** [mdn/developer-portal#903]
Set up back-syncing of Production state (DB and S3 user-media assets) from prod to staging.

    
AC:
- [ ] Staging's pages mirror the content of production in the rendered CMS pages
- [ ] Images uploaded to the production S3 assets bucket are available in the staging S3 assets bucket
- [ ] The staging static site is automatically updated (unless this is a lot of work to arrange)
- [ ] ~Need to be careful not to zap [dev] accounts on staging that may not exist in prod~

**Comment by stevejalim** [comment]
Updating the AC to remove the worry about accounts on dev -- we can overwrite them because all relevant parties have accounts in prod

**Comment by stevejalim** [comment]
@limed IIRC you said this might be less pain than expected. How long might it take, and what code/setup is needed, please?

**Comment by stevejalim** [comment]
This can happen during the dev-pause if you have time, @limed 

You'll likely have to re-run migrations on `dev` when the DB state has arrived on `dev`, because the code deployed there may well have some migrations that don't yet exist on prod, and will expect a certain, different, schema

**Comment by stevejalim** [comment]
I would backup Dev's DB before trying, just in case

**Comment by stevejalim** [comment]
Closing this because @valgrimm uses Stage as a playground to draft and test content and auto-overwriting of that would be a killer for her workflow.

Will make another ticket about creating a script that can do this on-demand rather than automatically.
