### ISSUE TITLE
Support linking to non-image files

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#905]
Option 1: Create an "External content" > type for files and add content links there to use throughout the site. Linked as external pages from a streamfield.
Option 2: Have File "Page type" (like Video pages). These be used to display presentations and linked as internal pages from a streamfield. 

Related to 907

**Comment by valgrimm** [comment]
Supports 545

**Comment by atopal** [comment]
we'll use 545 as the epic
