### ISSUE TITLE
Support upload of non-image files

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#907]
Example:
A presenter gives Val a Powerpoint or PDF of their slides.
Val uploads this to Wagtail. 
Val creates a "external link" to this page or a File page (related to 905)
Val links to this file from an event page as an "External content" > Files type (related to 905)

**Comment by stevejalim** [comment]
Is this a duplicate of #545 ?

**Comment by valgrimm** [comment]
Supports 545

**Comment by atopal** [comment]
we'll use 545 as the epic.
