### ISSUE TITLE
Lighthouse scores are sinking on heavy pages

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#923]
I've tweaked the URLs that Lighthouse targets to include some of the heavier pages (eg /posts/ and /events/) and we've dropped from 99/100 to 76/100 -- the pages are just too big.

This lends more weight/urgency to sorting out the pagination, so we don't load a ton of stuff we don't immediately need

**Comment by valgrimm** [comment]
Fixed. Created a video page to contain the playlist (https://developer.mozilla.com/videos/view-source-playlist/) that includes both an embed link to the list (which looks like only one video as only the first one is displayed) and a list of links to all the pages for these videos on the developer site.
This is not ideal, and there's got to be a better way to do this, but I am not sure where best to start from--creating a new page type or changing the options for video pages. I can discuss with Sandra this evening (3 December) and welcome other input.

View Source event page (revised):https://developer.mozilla.com/events/view-source-conference-2019/
Playlist https://developer.mozilla.com/videos/view-source-playlist/

**Comment by valgrimm** [comment]
Also going to fix this for the European roadshow. Issue resolved, most likely.

**Comment by stevejalim** [comment]
Reopening because this is more about the number of elements on /posts/ and on /events/ rather than specific Event pages, but I appreciate you making View Source lighter @valgrimm 👍

**Comment by valgrimm** [comment]
Sorry about that Steve. Also, going to make Roadshow 2019 Europe lighter as well. Events is definitely too long, what about just providing a link to a Past Events page and only listing future events with only the three soonest above a "See More Future Events" link? Could ask Sandra about, or perhaps this should be run by the UX designer first . . . What do you think @atopal ?

**Comment by stevejalim** [comment]
We could add a 'past-events' page, sure -- not sure if we could just have two Event pages and put different content in them, and link to one from the other -- something to experiment with on Staging perhaps.

**Comment by valgrimm** [comment]
I'd want to make the Past Events page not directly accessible. Also, since there is an auto-feed of past events, this would have to be done in the code. Actually a bit curious how this is done.

**Comment by stevejalim** [comment]
I think the Events page is pretty opinionated about what goes where and what is future vs past, so yeah I think that might well need code changes

**Comment by valgrimm** [comment]
I'll ask Sandra about this when we meet this evening.

**Comment by valgrimm** [comment]
Discussed with Sandra. She says is ok to have a separate past events page and list fewer (5 soonest) future events. Does change to events area need a different ticket that is a child of 923 @stevejalim

**Comment by atopal** [comment]
I don't think we need to find workarounds right now, the way forward is probably to do proper pagination on a dynamic site

**Comment by valgrimm** [comment]
Ok. Although Sandra agreed so fast that she seemed to think that prioritizing folks seeing future events was an end in itself. I could contact her for clarification and create a separate ticket.

**Comment by atopal** [comment]
Yeah, if that's a quick win, sure, let's do it.

**Comment by valgrimm** [comment]
Did pagination solve this, Steve?

**Comment by stevejalim** [comment]
When it's deployed it should, yes. But it's still waiting in the wings
