### ISSUE TITLE
Get the RRA and VA revisited re dynamic site

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#937]
AC 

- [ ] RRA and VA are up to date
- [ ] Service owner (@atopal) is comfortable with approach and any notes from the updated RRA and VA

**Comment by stevejalim** [comment]
Already talked throught his with MozInfoSec in Slack, but will formalise it using the appropriate proper channels

**Comment by stevejalim** [comment]
Posted an overview message in the official RRA thread, will see if additional info or a course-correction is needed

**Comment by stevejalim** [comment]
@atopal You may have seen this on the MozInfoSec ticket, but if not:

> --- Comment #27 from Caglar Ulucenk [:Cag] <culucenk@mozilla.com> ---
> Thanks Steve, I don't have a strong opinion about this change. I agree it does
> not change the risk profile in a big way.

So I'm happy to take that as a :thumbsup:

Can we close this ticket?

**Comment by atopal** [comment]
yes, we can
