### ISSUE TITLE
Drop the S3 buckets that hold the static site (stage and prod)

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#940]
AFTER we've moved away from the static approach we can clean up the S3 buckets

Acceptance Criteria
- [ ] staging static-site bucket is gone BUT S3 assets bucket remains
- [ ] production static-site bucket is gone BUT S3 assets bucket remains

**Comment by stevejalim** [comment]
I think this can happen (dropping the static-site buckets but NOT the asset ones (!) ) and then the parent Epic can be closed

cc @atopal @limed

**Comment by stevejalim** [comment]
@limed just giving this a bump - see comment above

**Comment by limed** [comment]
The origin for the CDN has been deleted, and the buckets emptied out and deleted as well
