### ISSUE TITLE
Add a post-Publish task that warms the CDN 

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#943]
Ideally we could add a post-Publish task that (after enough time for CDN invalidation to have taken place), warms the CDN by making a single request for every live page in the CMS. 

Note: Because CDN invalidation is not guaranteed to happen at a particular point, there is scope for race conditions/niggles here.

AC 

- [ ] _N_ minutes after we invalidate the entire CDN (see #942) we run a task that requests all published pages again (which we will get from the sitemap.xml)

Stretch:
- [ ] _N_ minutes after we invalidate special/selected pages in the CDN (such as /events/ see #942) we run a task that requests those just-invalidated keys again

**Comment by stevejalim** [comment]
@atopal So, thinking about this in more detail, it makes sense to warm the pages we get from sitemap.xml, but what this won't do is warm the variations of the pages that are possible via filters and pagination (indeed, the scale of these variations was a driver for me to decide on moving away from the static site - the number of permutation is large).

So, just flagging it now: warming the CDN for the sitemapped pages should
* improve first-load times for unfiltered versions of pages 

But it won't:
* guarantee that the CDN will give us a layer of "uptime protection" if the backend becomes unavailable, because not every permutation of every page will be pre-cached by the CDN

Hope that sits OK with you, in terms of user experience / product behaviour

**Comment by atopal** [comment]
That is okay with me Steve

**Comment by stevejalim** [comment]
Decided during code review that this is not worth the added complexity in exchange for a limited gain
