### ISSUE TITLE
Switch APP_HOST for stage

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#952]
Currently the `APP_HOST` variable is configured to `developer-portal-stage.mdn.mozit.cloud` this needs to be changed to `developer-portal.stage.mdn.mozit.cloud` to be in parity with prod

Once this is done the DNS records will need to be switched over as well

**Comment by stevejalim** [comment]
@limed Is this done now? I think it is, yeah?

**Comment by limed** [comment]
Yup this is done here b0a44fc3c99c46bfca1f391f1a4258bb2ef73b7a
