### ISSUE TITLE
Setup Horizontal Pod Autoscaler

### ISSUE THREAD

**Issue by limed** [mdn/developer-portal#954]
We don't have have Horizontal Pod Autoscaler (HPA) setup for developer-portal, we should at the very least add the manifest for prod

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by stevejalim** [comment]
Unless the cost is $$$$$$ can we have it for stage, too, to ensure complete parity between environments, please?

**Comment by limed** [comment]
All done
