### ISSUE TITLE
Rename topics to something more understandable

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#958]
...at least in the menu

See feedback doc for more context

**Comment by valgrimm** [comment]
Teams? Technologies? 

Kadir suggests base on user research

Not Research or Products . . .

Conclusion "Products and Technologies" for now. 
Val to implement. Do user research later.

**Comment by valgrimm** [comment]
Val to correct menu and adjust redirects in admin to ensure not breaking things
Test on Staging first

 . . . . 

Topics was envisioned for one purpose and is now serving another
originally seen as marginal way to find articles and videos related to specific things
Now it is core. This is why this matters.

**Comment by valgrimm** [comment]
Not going to do redirects, just change label in menu.

**Comment by valgrimm** [comment]
Done in menu. Have created #1010 for code change to title of on "Topics Panel" as it appears on homepage.
