### ISSUE TITLE
Move "How to Get Sponsorship for your Developer Event"

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#972]
Move out of Communities menu and on to Events page above events list
Steve will add a streamfield above events list and below Featured Event so this can be done
Val will then make the change

AC 
- [ ] Sponsporship link no longer visible in menu
- [x] Events page has streamfield below the featured block that allows adding arbitratry content
- [ ] That streamfield contains a button linking to the sponsorship page

**Comment by stevejalim** [comment]
@valgrimm @atopal I've added AC for this, but in addition, do we want do move where the sponsorship page lives in the CMS (ie, it's under `/community/`). I can add support to allow Events (/events/) to have child pages that are just regular Content Pages too, but that's a separate code change.

Put another way: shall we take the opportunity to allow the Events Page to have children that are Content Pages as well as Event pages? It's probably a couple of hours, incl QA

**Comment by valgrimm** [comment]
Hi Steve, thank you for this and the well-described proposed extension. 
I'm not sure in what other context we'll need non-Event child pages for the events area, so I propose skipping that extra functionality for now. (I'd like that for Topics, but that's another ticket and again not sure that is needed either). 

So short version, just move where the link appears, not where the content lives. 
Thanks!

**Comment by atopal** [comment]
+1 agreed, and yes, thanks for adding the AC!

**Comment by valgrimm** [comment]
Steve enabled adding the button, and I have added it to the events page to link to  "How to Get Sponsorship for your Developer Event", and removed  "How to Get Sponsorship for your Developer Event" from the Communities dropdown.
