### ISSUE TITLE
Support serving docs from official domain, not S3

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#985]
Once we move to a dynamic site, we can do this easily enough, but will need to ensure we enable the configuration option where Wagtail serves the doc, rather than just redirects to S3 and its non-elegant hostname

AC
- [ ] When downloading a document stored in wagtail, the user sees the production hostname throughout the download experience

**Comment by stevejalim** [comment]
@valgrimm @atopal I've looked into the code implications of this and chatted about things with @limed and here's my take:

* Serving those files from (a non-static) developer.mozilla.com isn't going to work, because of the need for `sendfile` support. (Minor: it puts additional load on the Kubernetes cluster, too)

* We can't put a pretty CNAME on the existing S3 bucket for assets without recreating it and copying over, because the name of the bucket needs to map to the CNAME you want.

* Less disruption is to add a new, separate CDN (poss with shorter cacheing) that ALSO points to the S3 bucket (ie, this gives us two roads to the same file) and _this_ CDN could have any domain name we want (eg, `assets.developer.mozilla.com` if we can get appropriate agreement). However, someone would need to manually create URLs to assets under this CNAME, because Django/Wagtail won't know anything about it, unless we change it for ALL assets to be served via it. (@limed - what do you thikn about this last sentence - could actually be fine)

**Comment by valgrimm** [comment]
Wow. That sounds like a lot of work for a "nice to have". What do you think, Kadir?

**Comment by atopal** [comment]
Yeah, I think we skip this for now.

**Comment by limed** [comment]
> Less disruption is to add a new, separate CDN (poss with shorter cacheing) that ALSO points to the S3 bucket (ie, this gives us two roads to the same file) and this CDN could have any domain name we want (eg, assets.developer.mozilla.com if we can get appropriate agreement). However, someone would need to manually create URLs to assets under this CNAME, because Django/Wagtail won't know anything about it, unless we change it for ALL assets to be served via it. (@limed - what do you thikn about this last sentence - could actually be fine)

Yup sounds about right, I mean another option is to just use a non pretty S3 bucket URL but at the end you will still need to reference the URL of the file and it will be in the form of `https://${bucketname}.s3.amazonaws.com` or something similar. This route is similar to the CDN route
