### ISSUE TITLE
Add a byline field to external posts type article

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#986]
AC
-Make field optional
-Display in smaller font, separate from title, below title
-Font size must allow 90 characters to fit into one line within card edges with 10px of padding
-Do not break across lines or overflow
-Field limit: less than 90 characters long, including spaces

**Comment by stevejalim** [comment]
@valgrimm Are the layout specs basically the same as the current ones for regular articles? If ot, I'd prefer we use whatever styling/layout rules apply to those bylines -- I remember that Potato worked carefully to tweak them to meet stakeholder wishes. Is that OK with you, please?

**Comment by valgrimm** [comment]
Well, regular article/post cards don't actually display a byline. Did a test. See image. I can add the author data, but only shows up on article/post page itself. 
<img width="834" alt="nobyline" src="https://user-images.githubusercontent.com/56933147/71008100-5cd22980-20e8-11ea-8adf-edab559fb899.PNG">
